//! Current product-specific mouse workspaces. CONFIG and mounted component receipts
//! are generated by tools/extract-mouse-products.cjs and extract-mouse-page-evidence.cjs.
//! Drafts preserve the source profile schema and never represent hardware writes.
use gpui_kit::component::{
    ActiveTheme, Disableable, Selectable, StyledExt,
    button::Button,
    checkbox::Checkbox,
    h_flex,
    input::{Input, InputEvent, InputState, MaskPattern},
    slider::{Slider, SliderEvent, SliderState},
    v_flex,
};
use gpui_kit::*;
use serde::Deserialize;
use serde_json::{Value, json};
use std::{collections::BTreeMap, sync::OnceLock};

use crate::i18n::t;
use crate::ui::surface;
#[path = "mouse_226_dpi.rs"]
mod dpi_grid;
#[path = "mouse_dpi_number.rs"]
mod dpi_number;
#[path = "mouse_dpi_rows.rs"]
mod dpi_rows;
#[path = "mouse_226_scroll.rs"]
mod scroll_wheel;
pub(crate) use scroll_wheel::ScrollWheelObservation;
#[path = "mouse_polling_view.rs"]
mod polling;
use super::mouse_polling::{
    MousePollingObservation, MousePollingScope, PollingConnection, PollingField,
};
#[path = "mouse_226_properties.rs"]
mod properties;

#[derive(Deserialize)]
pub(crate) struct MouseProductSpec {
    product_id: u32,
    profile: Value,
    min_dpi: u32,
    max_dpi: u32,
    dpi_step: u32,
    support_xy: bool,
    rates: BTreeMap<String, Vec<u32>>,
    effects: Vec<MouseEffect>,
    buttons: Vec<Value>,
    dkm: Vec<Value>,
    mats: Vec<Value>,
    calibration: String,
    smart_lift_max: u32,
    smart_landing_max: u32,
    power_slider: bool,
    performance_power: bool,
    low_power_slider: bool,
    low_battery_slider: bool,
    rotation: bool,
    dynamic: bool,
    pages: Vec<String>,
    image: Option<String>,
    groups: Vec<Value>,
}

#[derive(Deserialize)]
struct MouseEffect {
    key: String,
    id: u32,
}

impl MouseProductSpec {
    pub(crate) fn macro_groups(&self) -> &[Value] {
        &self.groups
    }
    pub(crate) fn macro_image(&self) -> Option<&str> {
        self.image.as_deref()
    }
    fn has_page(&self, key: &str) -> bool {
        self.pages.iter().any(|p| p == key)
    }
    fn stages_path(&self) -> &'static str {
        if self.profile.get("DPIStages").is_some() {
            "/DPIStages/Stages/DPIStage"
        } else {
            "/dpiStages/stages"
        }
    }
    fn active_path(&self) -> &'static str {
        if self.profile.get("DPIStages").is_some() {
            "/DPIStages/Active"
        } else {
            "/dpiStages/active"
        }
    }
    fn stage_enable_path(&self) -> &'static str {
        if self.profile.get("DPIStages").is_some() {
            "/DPIStages/State"
        } else {
            "/dpiStages/enable"
        }
    }
    fn dpi_axis(&self, axis: usize) -> &'static str {
        match (self.profile.get("DPIStages").is_some(), axis) {
            (true, 0) => "X",
            (true, _) => "Y",
            (false, 0) => "x",
            (false, _) => "y",
        }
    }
    fn independent_key(&self) -> &'static str {
        if self.profile.get("DPIStages").is_some() {
            "Independent"
        } else {
            "independent"
        }
    }
    fn has_dpi_number(&self, path: &str) -> bool {
        matches!(self.product_id, 70 | 226) && path.starts_with(self.stages_path())
    }
    fn visible_key(&self) -> &'static str {
        if self.profile.get("DPIStages").is_some() {
            "Active"
        } else {
            "visible"
        }
    }
    fn polling_path(&self) -> &'static str {
        if self.profile.get("PollingRate").is_some() {
            "/PollingRate"
        } else {
            "/pollingRate"
        }
    }
    fn power_path(&self) -> &'static str {
        if self.profile.get("PowerSavingValue").is_some() {
            "/PowerSavingValue"
        } else {
            "/powerSavingValue"
        }
    }
}

pub(crate) fn source_product(product_id: u32) -> Option<&'static MouseProductSpec> {
    static PRODUCTS: OnceLock<Vec<MouseProductSpec>> = OnceLock::new();
    PRODUCTS
        .get_or_init(|| {
            serde_json::from_str(include_str!("mouse_products_data.json"))
                .expect("validated current mouse product specifications")
        })
        .iter()
        .find(|product| product.product_id == product_id)
}

pub(crate) struct MouseProductChanged;

/// Retains native controls and edits only the currently selected source profile.
pub(crate) struct MouseProductWorkspace {
    spec: &'static MouseProductSpec,
    page: String,
    active: bool,
    draft: Value,
    sliders: BTreeMap<String, Entity<SliderState>>,
    inputs: BTreeMap<String, Entity<InputState>>,
    dpi_numbers: BTreeMap<String, dpi_number::EditState>,
    dpi_grids: BTreeMap<String, Entity<dpi_grid::GridState>>,
    dpi_dragged_row: Option<usize>,
    draft_generation: u64,
    dpi_editing_observed: Option<bool>,
    polling_state: polling::State,
    polling_owner: Option<EntityId>,
    properties_icon: Option<&'static str>,
    subscriptions: Vec<Subscription>,
    syncing: bool,
    scroll: ScrollHandle,
    mapping_input: Option<String>,
    hypershift: bool,
    group_ix: usize,
    scroll_editor: Option<Entity<scroll_wheel::ScrollWheelEditor>>,
}

impl EventEmitter<MouseProductChanged> for MouseProductWorkspace {}

impl MouseProductWorkspace {
    pub(crate) fn new(product_id: u32, window: &mut Window, cx: &mut Context<Self>) -> Self {
        let spec = source_product(product_id).expect("registered mouse product");
        let mut this = Self {
            spec,
            page: "TAB_CUSTOMIZE".into(),
            active: false,
            draft: spec.profile.clone(),
            sliders: BTreeMap::new(),
            inputs: BTreeMap::new(),
            dpi_numbers: BTreeMap::new(),
            dpi_grids: BTreeMap::new(),
            dpi_dragged_row: None,
            draft_generation: 0,
            dpi_editing_observed: None,
            polling_state: polling::State::default(),
            polling_owner: super::mouse_polling::source_spec(product_id).map(|_| cx.entity_id()),
            properties_icon: (product_id == 226).then(|| {
                if crate::backend::system::is_windows_11() {
                    "synapse/windows-11.svg"
                } else {
                    "synapse/windows.svg"
                }
            }),
            subscriptions: Vec::new(),
            syncing: false,
            scroll: ScrollHandle::new(),
            mapping_input: None,
            hypershift: false,
            group_ix: 0,
            scroll_editor: None,
        };
        this.prepare_controls(window, cx);
        if product_id == 226 {
            let editor = cx.new(|cx| scroll_wheel::ScrollWheelEditor::new(window, cx));
            this.subscriptions.push(cx.subscribe(
                &editor,
                |this, editor, _: &scroll_wheel::Changed, cx| {
                    let value = editor.read(cx).snapshot();
                    let fields = editor.read(cx).local_fields();
                    this.draft["scrollWheel"] = value;
                    this.draft[scroll_wheel::LOCAL_FIELDS] = fields;
                    cx.emit(MouseProductChanged);
                    cx.notify();
                },
            ));
            this.scroll_editor = Some(editor);
            this.draft[scroll_wheel::LOCAL_FIELDS] = json!([]);
            this.draft[polling::LOCAL_FIELDS] = json!([]);
        }
        this
    }

    pub(crate) fn set_page(&mut self, key: &str, window: &mut Window, cx: &mut Context<Self>) {
        if self.page != key {
            self.dismiss_editors(window, cx);
            self.page = key.into();
            self.mapping_input = None;
            self.scroll.set_offset(point(px(0.), px(0.)));
            cx.notify();
        }
    }

    pub(crate) fn snapshot(&self) -> Value {
        self.draft.clone()
    }
    pub(crate) fn set_active(&mut self, active: bool, window: &mut Window, cx: &mut Context<Self>) {
        if self.active != active {
            self.active = active;
            if !active {
                self.dismiss_editors(window, cx);
            }
            cx.notify();
        }
    }
    pub(crate) fn dismiss_editors(&mut self, window: &mut Window, cx: &mut Context<Self>) {
        if let Some(editor) = &self.scroll_editor {
            editor.update(cx, |editor, cx| editor.deactivate(window, cx));
        }
        self.dismiss_dpi_editors(window, cx);
    }
    fn dismiss_dpi_editors(&mut self, window: &mut Window, cx: &mut Context<Self>) {
        self.draft_generation = self.draft_generation.wrapping_add(1);
        self.dpi_dragged_row = None;
        for state in self.dpi_numbers.values_mut() {
            *state = dpi_number::EditState::default();
        }
        // The source unmounts the row's local numeric preview on leaving the page.
        // These retained controls must return to the committed draft as well.
        self.syncing = true;
        for path in self.dpi_numbers.keys() {
            if let Some(value) = self.draft.pointer(path).and_then(Value::as_i64) {
                if let Some(input) = self.inputs.get(path) {
                    input.update(cx, |input, cx| {
                        input.set_value(value.to_string(), window, cx)
                    });
                }
                if let Some(slider) = self.sliders.get(path) {
                    slider.update(cx, |slider, cx| slider.set_value(value as f32, window, cx));
                }
            }
        }
        self.syncing = false;
        self.reset_dpi_grids(window, cx);
        cx.notify();
    }

    pub(crate) fn restore(
        &mut self,
        value: Option<&Value>,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) {
        self.draft_generation = self.draft_generation.wrapping_add(1);
        self.draft = self.spec.profile.clone();
        self.dpi_dragged_row = None;
        if let (Some(target), Some(saved)) =
            (self.draft.as_object_mut(), value.and_then(Value::as_object))
        {
            target.extend(
                saved
                    .iter()
                    .map(|(key, value)| (key.clone(), value.clone())),
            );
        }
        self.mapping_input = None;
        self.restore_polling(value);
        if let Some(editor) = &self.scroll_editor {
            editor.update(cx, |editor, cx| {
                editor.restore(
                    value.and_then(|value| value.get("scrollWheel")),
                    value.and_then(|value| value.get(scroll_wheel::LOCAL_FIELDS)),
                    window,
                    cx,
                )
            });
            self.draft["scrollWheel"] = editor.read(cx).snapshot();
            self.draft[scroll_wheel::LOCAL_FIELDS] = editor.read(cx).local_fields();
        }
        for state in self.dpi_numbers.values_mut() {
            *state = dpi_number::EditState::default();
        }
        self.syncing = true;
        for (path, state) in &self.sliders {
            if path == "smart-preset" {
                let value = self.smart_preset();
                state.update(cx, |state, cx| state.set_value(value as f32, window, cx));
                continue;
            }
            if let Some(value) = self.draft.pointer(path).and_then(Value::as_f64) {
                state.update(cx, |state, cx| state.set_value(value as f32, window, cx));
            }
        }
        for (path, state) in &self.inputs {
            if let Some(value) = self.draft.pointer(path).and_then(Value::as_i64) {
                state.update(cx, |state, cx| {
                    state.set_value(value.to_string(), window, cx)
                });
            }
        }
        self.syncing = false;
        self.reset_dpi_grids(window, cx);
        cx.notify();
    }

    fn reset_dpi_grids(&self, window: &mut Window, cx: &mut Context<Self>) {
        for (path, grid) in &self.dpi_grids {
            grid.update(cx, |grid, cx| grid.reset(self.number(path), window, cx));
        }
    }
    fn dpi_editing_enabled(&self) -> bool {
        // Current 226 Pe.enableStages starts true; None is a source UI default,
        // not a successful OTFS query. Runtime observations never enter draft.
        self.active
            && self.page == "TAB_PERFORMANCE"
            && (self.spec.product_id != 226 || self.dpi_editing_observed.unwrap_or(true))
    }
    fn dpi_number_editable(&self, path: &str) -> bool {
        if !self.dpi_editing_enabled() || self.dpi_dragged_row.is_some() {
            return false;
        }
        let Some((stage, axis)) = path.rsplit_once('/') else {
            return false;
        };
        let Some(slot) = stage
            .rsplit('/')
            .next()
            .and_then(|slot| slot.parse::<usize>().ok())
        else {
            return false;
        };
        self.draft.pointer(stage).is_some()
            && (axis == self.spec.dpi_axis(0)
                || self.boolean(&format!("{stage}/{}", self.spec.independent_key())))
            && (self.boolean(self.spec.stage_enable_path())
                || self.number(self.spec.active_path()) as usize == slot + 1)
    }
    pub(crate) fn observe_dpi_editing_enabled(
        &mut self,
        enabled: bool,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) {
        if self.spec.product_id != 226 {
            return;
        }
        self.dpi_editing_observed = Some(enabled);
        if !enabled {
            self.dismiss_dpi_editors(window, cx);
        }
        cx.notify();
    }

    fn edit_dpi_grid(
        &mut self,
        path: &str,
        event: &dpi_grid::Edited,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) {
        let Some((stage, axis)) = path.rsplit_once('/') else {
            return;
        };
        let slot = stage
            .rsplit('/')
            .next()
            .and_then(|slot| slot.parse::<usize>().ok());
        let visible = self.boolean(&format!("{stage}/{}", self.spec.visible_key()));
        let shown = self.boolean(self.spec.stage_enable_path())
            || slot.is_some_and(|slot| self.number(self.spec.active_path()) as usize == slot + 1);
        let axis_enabled = axis == self.spec.dpi_axis(0)
            || self.boolean(&format!("{stage}/{}", self.spec.independent_key()));
        if self.page != "TAB_PERFORMANCE"
            || !self.dpi_editing_enabled()
            || !visible
            || !shown
            || !axis_enabled
            || self.dpi_dragged_row.is_some()
        {
            if let Some(grid) = self.dpi_grids.get(path) {
                grid.update(cx, |grid, cx| grid.reset(self.number(path), window, cx));
            }
            return;
        }
        let value = match event {
            dpi_grid::Edited::Preview(value) | dpi_grid::Edited::Commit(value) => *value,
        };
        self.finish_dpi_number(path);
        self.syncing = true;
        if let Some(slider) = self.sliders.get(path) {
            slider.update(cx, |slider, cx| slider.set_value(value, window, cx));
        }
        if let Some(input) = self.inputs.get(path) {
            input.update(cx, |input, cx| {
                input.set_value((value as u32).to_string(), window, cx)
            });
        }
        self.syncing = false;
        if matches!(event, dpi_grid::Edited::Commit(_)) {
            self.write_number(path, value, window, cx);
        } else {
            cx.notify();
        }
    }

    fn write(&mut self, path: &str, value: Value, cx: &mut Context<Self>) {
        if self.draft.pointer(path) == Some(&value) {
            return;
        }
        set_pointer(&mut self.draft, path, value);
        cx.emit(MouseProductChanged);
        cx.notify();
    }

    pub(crate) fn observe_scroll_wheel(
        &mut self,
        observation: ScrollWheelObservation,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) {
        if let Some(editor) = &self.scroll_editor {
            editor.update(cx, |editor, cx| editor.observe(observation, window, cx));
        }
    }

    fn write_number(
        &mut self,
        path: &str,
        value: f32,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) {
        set_pointer(&mut self.draft, path, json!(value as i64));
        if path == "/smartTracking/liftOffDistance"
            && self.number("/smartTracking/landingDistance") >= value
        {
            set_pointer(
                &mut self.draft,
                "/smartTracking/landingDistance",
                json!((value - 1.).max(1.) as i64),
            );
        }
        if path == "/smartTracking/landingDistance"
            && self.number("/smartTracking/liftOffDistance") <= value
        {
            set_pointer(
                &mut self.draft,
                "/smartTracking/liftOffDistance",
                json!((value + 1.).min(self.spec.smart_lift_max as f32) as i64),
            );
        }
        if path.starts_with(self.spec.stages_path()) && path.ends_with(self.spec.dpi_axis(0)) {
            if let Some((stage, _)) = path.rsplit_once('/') {
                if !self.boolean(&format!("{stage}/{}", self.spec.independent_key())) {
                    set_pointer(
                        &mut self.draft,
                        &format!("{stage}/{}", self.spec.dpi_axis(1)),
                        json!(value as i64),
                    );
                }
            }
        }
        // Current 70 cI / 226 Ms activate a visible row when its X/Y value changes;
        // editing an excluded row preserves the selected stage.
        if matches!(self.spec.product_id, 70 | 226) {
            if let Some(rest) = path.strip_prefix(&format!("{}/", self.spec.stages_path())) {
                if let Some((slot, axis)) = rest.split_once('/') {
                    if axis == self.spec.dpi_axis(0) || axis == self.spec.dpi_axis(1) {
                        if let Ok(slot) = slot.parse::<usize>() {
                            if self.draft.pointer(&format!(
                                "{}/{slot}/{}",
                                self.spec.stages_path(),
                                self.spec.visible_key()
                            )) == Some(&Value::Bool(true))
                            {
                                set_pointer(
                                    &mut self.draft,
                                    self.spec.active_path(),
                                    json!(slot + 1),
                                );
                            }
                        }
                    }
                }
            }
        }
        self.syncing = true;
        for (other_path, slider) in &self.sliders {
            if other_path == path && self.spec.product_id != 70 {
                continue;
            }
            if let Some(value) = self.draft.pointer(other_path).and_then(Value::as_f64) {
                if slider.read(cx).value().start() != value as f32 {
                    slider.update(cx, |slider, cx| slider.set_value(value as f32, window, cx));
                    if let Some(input) = self.inputs.get(other_path) {
                        input.update(cx, |input, cx| {
                            input.set_value((value as i64).to_string(), window, cx)
                        });
                    }
                }
            }
        }
        self.syncing = false;
        cx.emit(MouseProductChanged);
        cx.notify();
    }

    fn number(&self, path: &str) -> f32 {
        self.draft
            .pointer(path)
            .and_then(Value::as_f64)
            .unwrap_or(0.) as f32
    }

    fn boolean(&self, path: &str) -> bool {
        self.draft
            .pointer(path)
            .and_then(Value::as_bool)
            .unwrap_or(false)
    }

    fn add_range(
        &mut self,
        path: String,
        min: f32,
        max: f32,
        step: f32,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) {
        let value = self.number(&path);
        let slider = cx.new(|_| {
            SliderState::new()
                .min(min)
                .max(max)
                .step(step)
                .default_value(value)
        });
        let changed_path = path.clone();
        self.subscriptions.push(cx.subscribe_in(
            &slider,
            window,
            move |this, slider, event, window, cx| {
                if this.syncing {
                    return;
                }
                let SliderEvent::Change(value) = event else {
                    return;
                };
                if this.spec.has_dpi_number(&changed_path)
                    && (!this.dpi_number_editable(&changed_path)
                        || !changed_path.rsplit_once('/').is_some_and(|(stage, _)| {
                            this.boolean(&format!("{stage}/{}", this.spec.visible_key()))
                        }))
                {
                    let value = this.number(&changed_path);
                    this.syncing = true;
                    slider.update(cx, |slider, cx| slider.set_value(value, window, cx));
                    this.syncing = false;
                    return;
                }
                let value = value.start().clamp(min, max);
                this.write_number(&changed_path, value, window, cx);
                if let Some(input) = this.inputs.get(&changed_path).cloned() {
                    input.update(cx, |input, cx| {
                        input.set_value((value as i64).to_string(), window, cx)
                    });
                }
            },
        ));
        let dpi_number = self.spec.has_dpi_number(&path);
        if dpi_number {
            self.dpi_numbers
                .insert(path.clone(), dpi_number::EditState::default());
        }
        let input = cx.new(|cx| {
            let input = InputState::new(window, cx).default_value((value as i64).to_string());
            if dpi_number {
                input.mask_pattern(MaskPattern::None).validate(|text, _| {
                    let digits = text.strip_prefix('-').unwrap_or(text);
                    digits.len() <= 6 && digits.bytes().all(|byte| byte.is_ascii_digit())
                })
            } else {
                input
            }
        });
        let changed_path = path.clone();
        self.subscriptions.push(cx.subscribe_in(
            &input,
            window,
            move |this, input, event, window, cx| {
                if this.syncing {
                    return;
                }
                if dpi_number && !this.dpi_number_editable(&changed_path) {
                    this.dismiss_dpi_editors(window, cx);
                    return;
                }
                if dpi_number && matches!(event, InputEvent::Change) {
                    if let Some(state) = this.dpi_numbers.get_mut(&changed_path) {
                        state.typed = true;
                    }
                    cx.notify();
                }
                if dpi_number && matches!(event, InputEvent::PressEnter { .. }) {
                    window.blur(cx);
                    return;
                }
                if !matches!(event, InputEvent::Blur | InputEvent::PressEnter { .. }) {
                    return;
                }
                let value = match input.read(cx).value().parse::<f32>() {
                    Ok(value) => value,
                    Err(_) if dpi_number => 0.,
                    Err(_) => return,
                };
                let value = ((value / step).ceil() * step).clamp(min, max);
                if dpi_number {
                    this.finish_dpi_number(&changed_path);
                }
                this.write_number(&changed_path, value, window, cx);
                // 4230.handleBlur always replaces the draft with parseInput's
                // normalized text, including when the slider already equals it.
                if dpi_number {
                    this.syncing = true;
                    input.update(cx, |input, cx| {
                        input.set_value((value as i64).to_string(), window, cx)
                    });
                    this.syncing = false;
                }
                if let Some(slider) = this.sliders.get(&changed_path).cloned() {
                    this.syncing = true;
                    slider.update(cx, |slider, cx| slider.set_value(value, window, cx));
                    this.syncing = false;
                }
            },
        ));
        self.sliders.insert(path.clone(), slider);
        self.inputs.insert(path.clone(), input);
        if self.spec.product_id == 226 && self.spec.has_dpi_number(&path) {
            let model = &self.sliders[&path];
            let grid = cx.new(|cx| dpi_grid::GridState::new(model, window, cx));
            let changed_path = path.clone();
            self.subscriptions.push(cx.subscribe_in(
                &grid,
                window,
                move |this, _, event, window, cx| {
                    this.edit_dpi_grid(&changed_path, event, window, cx);
                },
            ));
            self.dpi_grids.insert(path, grid);
        }
    }

    fn prepare_controls(&mut self, window: &mut Window, cx: &mut Context<Self>) {
        let count = self
            .draft
            .pointer(self.spec.stages_path())
            .and_then(Value::as_array)
            .map_or(0, Vec::len);
        for slot in 0..count {
            for axis in 0..if self.spec.support_xy { 2 } else { 1 } {
                let path = format!(
                    "{}/{slot}/{}",
                    self.spec.stages_path(),
                    self.spec.dpi_axis(axis)
                );
                self.add_range(
                    path,
                    self.spec.min_dpi as f32,
                    self.spec.max_dpi as f32,
                    self.spec.dpi_step as f32,
                    window,
                    cx,
                );
            }
        }
        if self.spec.power_slider || self.spec.performance_power {
            self.add_range(self.spec.power_path().into(), 1., 15., 1., window, cx);
        }
        if self.spec.low_power_slider {
            self.add_range("/lowPowerMode".into(), 5., 100., 5., window, cx);
        }
        if self.spec.low_battery_slider {
            self.add_range("/lowBatteryEffects".into(), 5., 100., 5., window, cx);
        }
        if self.spec.has_page("TAB_LIGHTING") && self.draft.pointer("/brightness/value").is_some() {
            self.add_range("/brightness/value".into(), 0., 100., 1., window, cx);
            self.add_range(
                "/switchOffLighting/idleMinutes".into(),
                1.,
                15.,
                1.,
                window,
                cx,
            );
        }
        if self.spec.calibration.starts_with("smart") {
            self.add_range(
                "/smartTracking/trackingDistance".into(),
                1.,
                3.,
                1.,
                window,
                cx,
            );
            if self.spec.calibration == "smart_only" {
                self.add_range(
                    "/smartTracking/liftOffDistance".into(),
                    2.,
                    self.spec.smart_lift_max as f32,
                    1.,
                    window,
                    cx,
                );
                self.add_range(
                    "/smartTracking/landingDistance".into(),
                    1.,
                    self.spec.smart_landing_max as f32,
                    1.,
                    window,
                    cx,
                );
            } else {
                let slider = cx.new(|_| {
                    SliderState::new()
                        .min(1.)
                        .max(3.)
                        .step(1.)
                        .default_value(self.smart_preset() as f32)
                });
                self.subscriptions.push(cx.subscribe_in(
                    &slider,
                    window,
                    |this, _, event, _, cx| {
                        if this.syncing {
                            return;
                        }
                        if let SliderEvent::Change(value) = event {
                            let (landing, lift) = match value.start().round() as i32 {
                                1 => (1, 2),
                                2 => (1, 3),
                                _ => (2, 3),
                            };
                            let mut tracking = this.draft["smartTracking"].clone();
                            tracking["landingDistance"] = json!(landing);
                            tracking["liftOffDistance"] = json!(lift);
                            this.write("/smartTracking", tracking, cx);
                        }
                    },
                ));
                self.sliders.insert("smart-preset".into(), slider);
            }
        }
        if self.spec.rotation {
            self.add_range("/rotation/value".into(), -44., 44., 1., window, cx);
        }
        if self.spec.has_page("TAB_SCROLLING") {
            for direction in ["upDirection", "downDirection"] {
                self.add_range(
                    format!("/scrollWheelStages/scrollWheelStages/5/{direction}/scrollTension"),
                    0.,
                    100.,
                    1.,
                    window,
                    cx,
                );
                self.add_range(
                    format!("/scrollWheelStages/scrollWheelStages/5/{direction}/scrollSteps"),
                    8.,
                    96.,
                    1.,
                    window,
                    cx,
                );
            }
        }
    }

    fn range(
        &self,
        path: &str,
        label: &str,
        suffix: &str,
        enabled: bool,
        cx: &Context<Self>,
    ) -> AnyElement {
        let Some(slider) = self.sliders.get(path) else {
            return div().into_any_element();
        };
        let group = SharedString::from(format!("mouse-range-{path}"));
        let input = if self.spec.product_id == 226 && self.spec.has_dpi_number(path) {
            dpi_number::DpiNumber {
                path: path.to_owned(),
                group: group.clone(),
                input: self.inputs[path].clone(),
                owner: cx.entity().downgrade(),
                disabled: !enabled,
                min: self.spec.min_dpi,
                max: self.spec.max_dpi,
                typed: self.dpi_numbers.get(path).is_some_and(|state| state.typed),
            }
            .into_any_element()
        } else {
            Input::new(&self.inputs[path])
                .w_20()
                .disabled(!enabled)
                .into_any_element()
        };
        v_flex()
            .group(group)
            .gap_3()
            .w_full()
            // 182 `.widget .content{margin-bottom:15px}`
            .mb(surface::css(15.))
            .child(
                h_flex()
                    .justify_between()
                    .gap_4()
                    .child(label.to_owned())
                    .child(h_flex().gap_2().child(input).child(suffix.to_owned())),
            )
            .child(Slider::new(slider).disabled(!enabled))
            .child(
                h_flex()
                    .justify_between()
                    .text_xs()
                    .text_color(cx.theme().muted_foreground)
                    .child(format!("{}", slider.read(cx).min_value()))
                    .child(format!("{}", slider.read(cx).max_value())),
            )
            .into_any_element()
    }

    fn toggle(&self, path: &str, label: impl Into<String>, cx: &Context<Self>) -> AnyElement {
        let path = path.to_owned();
        // 182 `.check-item{margin-bottom:9px}`：勾选项之间靠这条外边距分行。
        div()
            .mb(surface::css(9.))
            .child(
                Checkbox::new(SharedString::from(format!(
                    "mouse-{}-{path}",
                    self.spec.product_id
                )))
                .label(label.into())
                .checked(self.boolean(&path))
                .on_click(cx.listener(move |this, checked, window, cx| {
                    this.write(&path, json!(*checked), cx);
                    if !checked
                        && path.starts_with(this.spec.stages_path())
                        && path.ends_with(this.spec.independent_key())
                    {
                        if let Some((stage, _)) = path.rsplit_once('/') {
                            let x_path = format!("{stage}/{}", this.spec.dpi_axis(0));
                            this.write_number(&x_path, this.number(&x_path), window, cx);
                        }
                    }
                })),
            )
            .into_any_element()
    }

    fn performance(&self, cx: &Context<Self>) -> AnyElement {
        if matches!(self.spec.product_id, 70 | 226) {
            let mut right = v_flex().gap_5();
            if super::mouse_polling::source_spec(self.spec.product_id).is_none()
                || self.source_polling_visible()
            {
                right = right.child(self.polling(cx));
            }
            if self.spec.product_id == 226 {
                right = right.child(self.mouse_properties(cx));
            }
            if self.spec.performance_power {
                right = right.child(self.power(cx));
            }
            return surface::page_columns()
                .child(surface::page_column(self.dpi_rows(cx)))
                .child(surface::page_column(right))
                .into_any_element();
        }
        let count = self
            .draft
            .pointer(self.spec.stages_path())
            .and_then(Value::as_array)
            .map_or(0, Vec::len);
        let active = self.number(self.spec.active_path()) as usize;
        let mut sensitivity = surface::panel(t("SENSITIVITY_HEADER"), cx)
            .child(self.toggle(self.spec.stage_enable_path(), t("SENSITIVITY_STAGES"), cx))
            .child(
                h_flex()
                    .flex_wrap()
                    .gap_2()
                    .children((0..count).map(|slot| {
                        let path = self.spec.active_path();
                        Button::new(SharedString::from(format!("mouse-dpi-stage-{slot}")))
                            .label((slot + 1).to_string())
                            .outline()
                            .selected(active == slot + 1)
                            .on_click(cx.listener(move |this, _, _, cx| {
                                this.write(path, json!(slot + 1), cx)
                            }))
                    })),
            );
        let slot = active.saturating_sub(1).min(count.saturating_sub(1));
        if count > 0 {
            let independent_path = format!(
                "{}/{slot}/{}",
                self.spec.stages_path(),
                self.spec.independent_key()
            );
            if self.spec.support_xy {
                sensitivity = sensitivity.child(self.toggle(&independent_path, t("ENABLE_XY"), cx));
            }
            for axis in 0..if self.spec.support_xy && self.boolean(&independent_path) {
                2
            } else {
                1
            } {
                let path = format!(
                    "{}/{slot}/{}",
                    self.spec.stages_path(),
                    self.spec.dpi_axis(axis)
                );
                sensitivity = sensitivity.child(self.range(
                    &path,
                    if self.spec.support_xy {
                        if axis == 0 { "X" } else { "Y" }
                    } else {
                        "DPI"
                    },
                    "DPI",
                    true,
                    cx,
                ));
            }
        }
        let mut right = v_flex().gap_5().child(self.polling(cx));
        if self.spec.performance_power {
            right = right.child(self.power(cx));
        }
        surface::page_columns()
            .child(surface::page_column(sensitivity))
            .child(surface::page_column(right))
            .into_any_element()
    }

    fn polling(&self, cx: &Context<Self>) -> AnyElement {
        if super::mouse_polling::source_spec(self.spec.product_id).is_some() {
            return self.source_polling_panel(cx);
        }
        let path = self.spec.polling_path();
        let rates = self
            .spec
            .rates
            .get("POLLING_RATE")
            .map(Vec::as_slice)
            .unwrap_or(&[]);
        surface::panel(t("POLLING_RATE_HEADER"), cx)
            .child(
                h_flex()
                    .flex_wrap()
                    .gap_2()
                    .children(rates.iter().map(|rate| {
                        let rate = *rate;
                        Button::new(SharedString::from(format!("mouse-polling-{rate}")))
                            .label(format!("{rate} Hz"))
                            .outline()
                            .selected(self.number(path) as u32 == rate)
                            .on_click(
                                cx.listener(move |this, _, _, cx| {
                                    this.write(path, json!(rate), cx)
                                }),
                            )
                    })),
            )
            .into_any_element()
    }

    fn power(&self, cx: &Context<Self>) -> AnyElement {
        let mut panels = v_flex().gap_5();
        if self.spec.power_slider || self.spec.performance_power {
            panels = panels.child(
                surface::panel(t("POWER_SAVING_HEADER"), cx)
                    .child(surface::note(t("POWER_SAVING_DESC"), cx))
                    .child(self.range(self.spec.power_path(), "", "", true, cx)),
            );
        }
        if self.spec.low_power_slider {
            panels = panels.child(
                surface::panel(t("LOW_POWER_MODE_HEADER"), cx)
                    .child(surface::note(t("LOW_POWER_MODE_DESC"), cx))
                    .child(self.range("/lowPowerMode", "", "%", true, cx)),
            );
        }
        if self.spec.low_battery_slider {
            panels = panels.child(
                surface::panel(t("LOW_BATTERY_EFFECTS_HEADER"), cx)
                    .child(surface::note(t("LOW_BATTERY_EFFECTS_DESC"), cx))
                    .child(self.range("/lowBatteryEffects", "", "%", true, cx)),
            );
        }
        panels.into_any_element()
    }

    /// The `displayMode=chromaApp` popup mounts this page without the product
    /// chrome; the renderer itself is shared, so no separate layout is faked.
    pub(crate) fn lighting_element(
        &self,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) -> AnyElement {
        self.lighting(window, cx)
    }

    /// The lighting page (`ql`): the left `.widget-col` holds the brightness
    /// widget (`WI` — title `BRIGHTNESS_HEADER`, tips `BRIGHTNESS_TOOLTIP`,
    /// `hasSwitch:true`, slider tags `0`/`100`) and the switch-off-lighting
    /// widget (`kI`/`xI` — title `SWITCH_OFF_LIGHTING_HEADER`, tips
    /// `SWITCH_OFF_LIGHTING_TOOLTIP`, `extraClass:"has-slider"`), the right one
    /// the quick-effects widget.
    fn lighting(&self, window: &mut Window, cx: &mut Context<Self>) -> AnyElement {
        let enabled = self.boolean("/brightness/isEnabled");
        surface::page_columns()
            .child(surface::page_column(
                v_flex()
                    .child(
                        surface::panel_with_title_switch(
                            t("BRIGHTNESS_HEADER"),
                            surface::SynapseSwitch::new("mouse-brightness")
                                .accessibility_label(t("BRIGHTNESS_HEADER"))
                                .checked(enabled)
                                .on_change(cx.listener(|this, next: &bool, _, cx| {
                                    this.write("/brightness/isEnabled", json!(*next), cx);
                                })),
                            surface::help_control("mouse-brightness-help", t("BRIGHTNESS_TOOLTIP")),
                            cx,
                        )
                        .child(surface::slider_tags("0", None, "100", None))
                        .child(self.range(
                            "/brightness/value",
                            crate::i18n::t("BRIGHTNESS_HEADER").as_str(),
                            "%",
                            enabled,
                            cx,
                        )),
                    )
                    .child(self.switch_off_lighting(window, cx)),
            ))
            .child(surface::page_column(
                surface::panel(t("QUICK_EFFECTS"), cx).child(
                    h_flex()
                        .flex_wrap()
                        .gap_2()
                        .children(self.spec.effects.iter().map(|effect| {
                            let id = effect.id;
                            Button::new(SharedString::from(format!("mouse-effect-{id}")))
                                .label(localized_name(effect_label(&effect.key), &effect.key))
                                .outline()
                                .selected(
                                    self.number("/quickEffects/selectedEffectId") as u32 == id,
                                )
                                .on_click(cx.listener(move |this, _, _, cx| {
                                    this.write("/quickEffects/selectedEffectId", json!(id), cx)
                                }))
                        })),
                ),
            ))
            .into_any_element()
    }

    /// `kI`/`xI`: the switch-off-lighting widget — check items `DISPLAY_TURNED_OFF`
    /// and (unless `DeviceInfo.hideLightingIdle`) `IDLE_FOR_MIN`, the latter
    /// followed by the 1–15 minute slider tagged `1`/`15` with no label
    /// (`.has-slider .slider-container{margin-left:30px;width:490px}`).
    fn switch_off_lighting(&self, window: &mut Window, cx: &mut Context<Self>) -> AnyElement {
        let brightness_on = self.boolean("/brightness/isEnabled");
        let display_on = self.boolean("/switchOffLighting/isDisplayOn");
        let idle_on = self.boolean("/switchOffLighting/isIdleEnabled");
        let mut widget = surface::panel_with_control(
            t("SWITCH_OFF_LIGHTING_HEADER"),
            surface::help_control(
                "mouse-switch-off-lighting-help",
                t("SWITCH_OFF_LIGHTING_TOOLTIP"),
            ),
            cx,
        )
        .child(
            surface::check_item(
                "mouse-switch-off-display",
                t("DISPLAY_TURNED_OFF"),
                display_on,
                !brightness_on,
                window,
                cx,
            )
            .on_click(cx.listener(move |this, _, _, cx| {
                this.write("/switchOffLighting/isDisplayOn", json!(!display_on), cx)
            })),
        );
        // 原版按 `Te.DeviceInfo.hideLightingIdle` 决定是否渲染空闲行；本地鼠标
        // 规格里没有这个设备字段（键盘规格有），因此走原版未设置该标志时的分支。
        {
            widget = widget
                .child(
                    surface::check_item(
                        "mouse-switch-off-idle",
                        t("IDLE_FOR_MIN"),
                        idle_on,
                        !brightness_on,
                        window,
                        cx,
                    )
                    .on_click(cx.listener(move |this, _, _, cx| {
                        this.write("/switchOffLighting/isIdleEnabled", json!(!idle_on), cx)
                    })),
                )
                .child({
                    let mut column = v_flex().ml(surface::css(30.)).w(surface::css(490.));
                    if let Some(slider) = self.sliders.get("/switchOffLighting/idleMinutes") {
                        column =
                            column.child(Slider::new(slider).disabled(!(brightness_on && idle_on)));
                    }
                    column.child(surface::slider_tags("1", None, "15", None))
                });
        }
        widget.into_any_element()
    }

    fn calibration(&self, cx: &Context<Self>) -> AnyElement {
        if self.spec.calibration.starts_with("smart") {
            let asymmetric = self.boolean("/smartTracking/isAsymmetric");
            let mut panel = surface::panel(t("SMARTTRACKING"), cx).child(self.toggle(
                "/smartTracking/isAsymmetric",
                t("ENABLEASYMMETRICCUTOFF"),
                cx,
            ));
            if asymmetric && self.spec.calibration == "smart_only" {
                panel = panel
                    .child(self.range(
                        "/smartTracking/liftOffDistance",
                        &t("LIFTOFFDISTANCE"),
                        "",
                        true,
                        cx,
                    ))
                    .child(self.range(
                        "/smartTracking/landingDistance",
                        &t("LANDINGDISTANCE"),
                        "",
                        true,
                        cx,
                    ));
            } else if asymmetric {
                panel = panel
                    .child(
                        h_flex()
                            .justify_between()
                            .child(format!(
                                "{}: {} mm",
                                t("LANDINGDISTANCE"),
                                self.number("/smartTracking/landingDistance")
                            ))
                            .child(format!(
                                "{}: {} mm",
                                t("LIFTOFFDISTANCE"),
                                self.number("/smartTracking/liftOffDistance")
                            )),
                    )
                    .child(Slider::new(&self.sliders["smart-preset"]));
            } else {
                panel = panel.child(self.range(
                    "/smartTracking/trackingDistance",
                    &t("TRACKINGDISTANCE"),
                    "",
                    true,
                    cx,
                ));
            }
            return surface::page_columns()
                .child(surface::page_column(panel))
                .into_any_element();
        }
        surface::page_columns()
            .child(surface::page_column(
                surface::panel(t("MOUSE_MAT_CALIBRATION_HEADER"), cx).children(
                    self.spec
                        .mats
                        .iter()
                        .filter_map(|mat| mat.get("id").and_then(Value::as_str))
                        .map(|mat| {
                            let mat = mat.to_owned();
                            Button::new(SharedString::from(format!("mouse-surface-{mat}")))
                                .label(mat.replace('_', " "))
                                .outline()
                                .selected(
                                    self.draft
                                        .pointer("/calibration/selectedSurface")
                                        .and_then(Value::as_str)
                                        == Some(mat.as_str()),
                                )
                                .on_click(cx.listener(move |this, _, _, cx| {
                                    this.write("/calibration/selectedSurface", json!(mat), cx)
                                }))
                        }),
                ),
            ))
            .into_any_element()
    }
    fn smart_preset(&self) -> u32 {
        if self.number("/smartTracking/liftOffDistance") == 2. {
            1
        } else if self.number("/smartTracking/landingDistance") == 1. {
            2
        } else {
            3
        }
    }

    fn advanced(&self, cx: &Context<Self>) -> AnyElement {
        let mut panels = surface::page_columns();
        if self.spec.dynamic {
            panels = panels.child(surface::page_column(
                surface::panel(t("DYNAMIC_SENSITIVITY"), cx)
                    .child(
                        Checkbox::new("mouse-dynamic-enabled")
                            .label(t("DYNAMIC_SENSITIVITY"))
                            .checked(self.number("/dynamicSensitivity/state") == 1.)
                            .on_click(cx.listener(|this, value, _, cx| {
                                this.write(
                                    "/dynamicSensitivity/state",
                                    json!(if *value { 1 } else { 0 }),
                                    cx,
                                )
                            })),
                    )
                    .child(
                        h_flex().gap_2().children(
                            ["CLASSIC", "NATURAL", "JUMP", "CUSTOM"]
                                .into_iter()
                                .enumerate()
                                .map(|(mode, key)| {
                                    Button::new(SharedString::from(format!("mouse-dynamic-{mode}")))
                                        .label(t(key))
                                        .outline()
                                        .selected(
                                            self.number("/dynamicSensitivity/mode") as usize
                                                == mode,
                                        )
                                        .on_click(cx.listener(move |this, _, _, cx| {
                                            this.write("/dynamicSensitivity/mode", json!(mode), cx)
                                        }))
                                }),
                        ),
                    ),
            ));
        }
        if self.spec.rotation {
            panels = panels.child(surface::page_column(
                surface::panel(t("ROTATION"), cx)
                    .child(self.toggle("/rotation/isEnabled", t("ROTATION"), cx))
                    .child(self.range(
                        "/rotation/value",
                        &t("ROTATION"),
                        "°",
                        self.boolean("/rotation/isEnabled"),
                        cx,
                    )),
            ));
        }
        panels.into_any_element()
    }

    fn scrolling(&self, cx: &Context<Self>) -> AnyElement {
        let stages = [
            "SW_STANDARD",
            "SW_DISTINCT",
            "SW_ULTRA_FINE",
            "SW_ADAPTIVE",
            "SW_SMOOTH_SCROLL",
            "SW_CUSTOM",
        ];
        let active = self
            .draft
            .pointer("/scrollWheelStages/activeStage")
            .and_then(Value::as_str)
            .unwrap_or("SW_STANDARD");
        let mut panel = surface::panel(t("SCROLL_WHEEL_STAGES"), cx)
            .child(surface::note(t("SCROLL_WHEEL_STAGES_DESCRIPTION"), cx))
            .child(
                h_flex()
                    .flex_wrap()
                    .gap_2()
                    .children(stages.into_iter().map(|stage| {
                        Button::new(SharedString::from(format!("mouse-wheel-{stage}")))
                            .label(t(stage))
                            .outline()
                            .selected(active == stage)
                            .on_click(cx.listener(move |this, _, _, cx| {
                                this.write("/scrollWheelStages/activeStage", json!(stage), cx)
                            }))
                    })),
            );
        if active == "SW_CUSTOM" {
            for (direction, key) in [
                ("upDirection", "SCROLL_UP"),
                ("downDirection", "SCROLL_DOWN"),
            ] {
                panel = panel
                    .child(div().child(t(key)))
                    .child(self.range(
                        &format!(
                            "/scrollWheelStages/scrollWheelStages/5/{direction}/scrollTension"
                        ),
                        &t("SCROLL_TENSION"),
                        "",
                        true,
                        cx,
                    ))
                    .child(self.range(
                        &format!("/scrollWheelStages/scrollWheelStages/5/{direction}/scrollSteps"),
                        &t("SCROLL_STEPS"),
                        "",
                        true,
                        cx,
                    ));
            }
        }
        surface::page_columns()
            .child(surface::page_column(panel))
            .into_any_element()
    }

    /// The `displayMode=armory` root mounts this page without the product
    /// chrome; the renderer itself is shared, so no separate layout is faked.
    pub(crate) fn customize_element(&self, cx: &mut Context<Self>) -> AnyElement {
        self.customize(cx)
    }

    fn customize(&self, cx: &Context<Self>) -> AnyElement {
        let mut buttons: Vec<&Value> = self
            .spec
            .groups
            .get(self.group_ix)
            .and_then(|group| group["buttonList"].as_array())
            .map(|buttons| buttons.iter().collect())
            .unwrap_or_default();
        if self.spec.groups.is_empty() {
            for button in self.spec.buttons.iter().chain(&self.spec.dkm) {
                if button["inputID"].is_string()
                    && !buttons
                        .iter()
                        .any(|other| other["inputID"] == button["inputID"])
                {
                    buttons.push(button);
                }
            }
        }
        let mut panel = surface::panel(t("TAB_CUSTOMIZE"), cx)
            .child(
                h_flex()
                    .gap_2()
                    .children(
                        self.spec
                            .groups
                            .iter()
                            .enumerate()
                            .filter_map(|(ix, group)| {
                                let name = group["groupName"].as_str()?.to_owned();
                                Some(
                                    Button::new(SharedString::from(format!("mouse-view-{name}")))
                                        .label(name)
                                        .outline()
                                        .selected(ix == self.group_ix)
                                        .on_click(cx.listener(move |this, _, _, cx| {
                                            this.group_ix = ix;
                                            this.mapping_input = None;
                                            cx.notify();
                                        })),
                                )
                            }),
                    ),
            )
            .children(
                self.spec
                    .image
                    .as_ref()
                    .filter(|_| self.group_ix == 0)
                    .map(|image| {
                        div().w_full().flex().justify_center().child(
                            img(SharedString::from(image.clone()))
                                .w(surface::css(300.))
                                .object_fit(ObjectFit::Contain),
                        )
                    }),
            )
            .child(
                Checkbox::new("mouse-hypershift")
                    .label("Razer Hypershift")
                    .checked(self.hypershift)
                    .on_click(cx.listener(|this, value, _, cx| {
                        this.hypershift = *value;
                        cx.notify();
                    })),
            )
            .children(buttons.iter().filter_map(|button| {
                let input = button["inputID"].as_str()?.to_owned();
                let label = localized_name(input_label(&input), &input);
                Some(
                    Button::new(SharedString::from(format!("mouse-input-{input}")))
                        .label(label)
                        .outline()
                        .disabled(!button["isEnabled"].as_bool().unwrap_or(true))
                        .selected(self.mapping_input.as_ref() == Some(&input))
                        .on_click(cx.listener(move |this, _, _, cx| {
                            this.mapping_input = Some(input.clone());
                            cx.notify();
                        })),
                )
            }));
        if let Some(input) = self.mapping_input.clone() {
            let source_button = buttons
                .iter()
                .find(|button| button["inputID"].as_str() == Some(&input));
            let supported = source_button.is_some_and(|button| {
                button["isEnabled"].as_bool().unwrap_or(true)
                    && button["functionList"].as_array().is_none_or(|functions| {
                        functions
                            .iter()
                            .any(|function| function == "MOUSE_FUNCTION")
                    })
            });
            if supported {
                panel = panel.child(
                    div()
                        .font_bold()
                        .child(localized_name(input_label(&input), &input)),
                )
                .child(Button::new("mouse-reset-mapping").label(t("DEFAULT")).outline().on_click(cx.listener({
                    let input=input.clone();
                    move |this,_,_,cx| {
                        if let Some(mappings)=this.draft["mappings"].as_array_mut() {
                            mappings.retain(|mapping| !(mapping["inputID"] == input && mapping["isHyperShift"].as_bool().unwrap_or(false)==this.hypershift));
                            cx.emit(MouseProductChanged);cx.notify();
                        }
                    }
                })))
                .child(h_flex().gap_2().flex_wrap().children([
                    ("Click", "LEFT_CLICK"), ("Menu", "RIGHT_CLICK"), ("ScrollButton", "SCROLL_CLICK"),
                    ("Previous", "STEP_BACK"), ("Next", "STEP_FORWARD"), ("ScrollUp", "SCROLL_UP"), ("ScrollDown", "SCROLL_DOWN"),
                ].into_iter().map(|(assignment, key)| {
                    let input = input.clone();
                    let input_type = source_button.and_then(|button| button["inputType"].as_str()).unwrap_or("MouseInput").to_owned();
                    Button::new(SharedString::from(format!("mouse-assignment-{assignment}"))).label(t(key)).outline()
                        .on_click(cx.listener(move |this, _, _, cx| {
                            let entry = json!({"inputID":input,"isHyperShift":this.hypershift,"inputType":input_type,"outputType":"mouseGroup","mouseGroup":{"mouseAssignment":assignment}});
                            let mappings = this.draft.get_mut("mappings").and_then(Value::as_array_mut);
                            if let Some(mappings) = mappings {
                                mappings.retain(|m| !(m["inputID"] == input && m["isHyperShift"].as_bool().unwrap_or(false) == this.hypershift));
                                mappings.push(entry);
                                cx.emit(MouseProductChanged); cx.notify();
                            }
                        }))
                })));
            }
        }
        if self.scroll_editor.is_none() && self.draft.get("scrollWheel").is_some() {
            panel = panel
                .child(self.toggle("/scrollWheel/smartReelEnabled", t("SMART_REEL"), cx))
                .child(self.toggle(
                    "/scrollWheel/accelerationEnabled",
                    t("SCROLL_ACCELERATION"),
                    cx,
                ));
        }
        v_flex()
            .child(surface::page_columns().child(surface::page_column(panel)))
            .children(
                self.scroll_editor.as_ref().map(|editor| {
                    surface::page_columns().child(surface::page_column(editor.clone()))
                }),
            )
            .into_any_element()
    }
}

impl Render for MouseProductWorkspace {
    fn render(&mut self, window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        let content = match self.page.as_str() {
            "TAB_PERFORMANCE" => self.performance(cx),
            "TAB_POWER" => self.power(cx),
            "TAB_LIGHTING" => self.lighting(window, cx),
            "TAB_CALIBRATION" => self.calibration(cx),
            "TAB_SCROLLING" => self.scrolling(cx),
            "ADVANCED" => self.advanced(cx),
            "TAB_PAIRING" => surface::panel(t("PAIR"), cx)
                .child(surface::note("配对界面尚未接入。", cx))
                .into_any_element(),
            "TAB_CUSTOMIZE" => self.customize(cx),
            _ => surface::panel(crate::i18n::t(&self.page), cx)
                .child(surface::note("此页面的原生控件仍在接入。", cx))
                .into_any_element(),
        };
        div()
            .id("mouse-product-body")
            .size_full()
            .min_h_0()
            .overflow_y_scroll()
            .track_scroll(&self.scroll)
            .child(super::product_surface::body().child(content))
    }
}

fn set_pointer(root: &mut Value, path: &str, value: Value) {
    let parts: Vec<_> = path.trim_start_matches('/').split('/').collect();
    let mut cursor = root;
    for part in &parts[..parts.len().saturating_sub(1)] {
        if cursor.is_array() {
            let Some(next) = part
                .parse::<usize>()
                .ok()
                .and_then(|index| cursor.get_mut(index))
            else {
                return;
            };
            cursor = next;
        } else {
            if !cursor.is_object() {
                *cursor = json!({});
            }
            cursor = cursor
                .as_object_mut()
                .unwrap()
                .entry((*part).to_owned())
                .or_insert_with(|| json!({}));
        }
    }
    if let Some(last) = parts.last() {
        if cursor.is_object() {
            cursor[*last] = value;
        }
    }
}

#[cfg(test)]
#[path = "mouse_products_tests.rs"]
mod tests;

/// 源码把鼠标输入映射为语言键（`LEFT_CLICK`、`STEP_BACK`…）；未知输入返回 `None`，
/// 由 [`localized_name`] 原样显示内部名。
fn input_label(input: &str) -> Option<&'static str> {
    Some(match input {
        "LeftClick" | "Click" => "LEFT_CLICK",
        "RightClick" | "Menu" => "RIGHT_CLICK",
        "ScrollButton" | "ScrollClick" => "SCROLL_CLICK",
        "ScrollUp" => "SCROLL_UP",
        "ScrollDown" => "SCROLL_DOWN",
        "Button4" | "Previous" => "STEP_BACK",
        "Button5" | "Next" => "STEP_FORWARD",
        "DoubleClick" => "DOUBLE_CLICK",
        "SensitivityStageUp" => "SENSITIVITY_STAGE_UP",
        "SensitivityStageDown" => "SENSITIVITY_STAGE_DOWN",
        "CycleUpSensitivityStages" => "CYCLE_UP_SENSITIVITY",
        "CycleUpProfile" => "CYCLE_UP_PROFILE",
        _ => return None,
    })
}

/// 源码效果表（`Mi` / `I`）把每个效果映射到语言键；未知效果返回 `None`。
fn effect_label(effect: &str) -> Option<&'static str> {
    Some(match effect {
        "Static_Effect" => "STATIC",
        "Breathing_Effect" => "BREATHING",
        "Spectrum_Effect" => "SPECTRUM_CYCLING",
        "Wave_Effect" => "WAVE",
        "Reactive_Effect" => "REACTIVE",
        "Ripple_Effect" => "RIPPLE",
        "Starlight_Effect" => "STARLIGHT",
        "Fire_Effect" => "FIRE",
        "Wheel_Effect" => "WHEEL",
        "Audio_Meter_Effect" => "AUDIO_METER",
        "Tidal_Effect" => "TIDAL",
        "Battery_Level_Effect" => "BATTERY_LEVEL",
        "Lamborghini" => "LAMBORGHINI",
        "Ambient_Effect" => "AMBIENT",
        _ => return None,
    })
}

/// 命中源码语言键就取译文，否则原样显示内部名（原版对未知项也是原样显示）。
fn localized_name(key: Option<&'static str>, raw: &str) -> String {
    key.map_or_else(|| raw.to_owned(), crate::i18n::t)
}
