//! Current product-specific mouse workspaces. CONFIG and mounted component receipts
//! are generated by tools/extract-mouse-products.cjs and extract-mouse-page-evidence.cjs.
//! Drafts preserve the source profile schema and never represent hardware writes.
use gpui_kit::component::{
    ActiveTheme, Disableable, Selectable, StyledExt,
    button::Button,
    checkbox::Checkbox,
    h_flex,
    input::{Input, InputEvent, InputState},
    slider::{Slider, SliderEvent, SliderState},
    v_flex,
};
use gpui_kit::*;
use serde::Deserialize;
use serde_json::{Value, json};
use std::{collections::BTreeMap, sync::OnceLock};

use crate::ui::surface;

#[derive(Deserialize)]
pub(crate) struct MouseProductSpec {
    product_id: u32,
    profile: Value,
    min_dpi: u32,
    max_dpi: u32,
    dpi_step: u32,
    support_xy: bool,
    rates: BTreeMap<String, Vec<u32>>,
    effects: Vec<MouseEffect>,
    buttons: Vec<Value>,
    dkm: Vec<Value>,
    mats: Vec<Value>,
    calibration: String,
    smart_lift_max: u32,
    smart_landing_max: u32,
    power_slider: bool,
    performance_power: bool,
    low_power_slider: bool,
    low_battery_slider: bool,
    rotation: bool,
    dynamic: bool,
    pages: Vec<String>,
    image: Option<String>,
    groups: Vec<Value>,
}

#[derive(Deserialize)]
struct MouseEffect {
    key: String,
    id: u32,
}

impl MouseProductSpec {
    fn has_page(&self, key: &str) -> bool {
        self.pages.iter().any(|p| p == key)
    }
    fn stages_path(&self) -> &'static str {
        if self.profile.get("DPIStages").is_some() {
            "/DPIStages/Stages/DPIStage"
        } else {
            "/dpiStages/stages"
        }
    }
    fn active_path(&self) -> &'static str {
        if self.profile.get("DPIStages").is_some() {
            "/DPIStages/Active"
        } else {
            "/dpiStages/active"
        }
    }
    fn stage_enable_path(&self) -> &'static str {
        if self.profile.get("DPIStages").is_some() {
            "/DPIStages/State"
        } else {
            "/dpiStages/enable"
        }
    }
    fn dpi_axis(&self, axis: usize) -> &'static str {
        match (self.profile.get("DPIStages").is_some(), axis) {
            (true, 0) => "X",
            (true, _) => "Y",
            (false, 0) => "x",
            (false, _) => "y",
        }
    }
    fn independent_key(&self) -> &'static str {
        if self.profile.get("DPIStages").is_some() {
            "Independent"
        } else {
            "independent"
        }
    }
    fn polling_path(&self) -> &'static str {
        if self.profile.get("PollingRate").is_some() {
            "/PollingRate"
        } else {
            "/pollingRate"
        }
    }
    fn power_path(&self) -> &'static str {
        if self.profile.get("PowerSavingValue").is_some() {
            "/PowerSavingValue"
        } else {
            "/powerSavingValue"
        }
    }
}

pub(crate) fn source_product(product_id: u32) -> Option<&'static MouseProductSpec> {
    static PRODUCTS: OnceLock<Vec<MouseProductSpec>> = OnceLock::new();
    PRODUCTS
        .get_or_init(|| {
            serde_json::from_str(include_str!("mouse_products_data.json"))
                .expect("validated current mouse product specifications")
        })
        .iter()
        .find(|product| product.product_id == product_id)
}

pub(crate) struct MouseProductChanged;

/// Retains native controls and edits only the currently selected source profile.
pub(crate) struct MouseProductWorkspace {
    spec: &'static MouseProductSpec,
    page: String,
    draft: Value,
    sliders: BTreeMap<String, Entity<SliderState>>,
    inputs: BTreeMap<String, Entity<InputState>>,
    subscriptions: Vec<Subscription>,
    syncing: bool,
    scroll: ScrollHandle,
    mapping_input: Option<String>,
    hypershift: bool,
    group_ix: usize,
}

impl EventEmitter<MouseProductChanged> for MouseProductWorkspace {}

impl MouseProductWorkspace {
    pub(crate) fn new(product_id: u32, window: &mut Window, cx: &mut Context<Self>) -> Self {
        let spec = source_product(product_id).expect("registered mouse product");
        let mut this = Self {
            spec,
            page: "TAB_CUSTOMIZE".into(),
            draft: spec.profile.clone(),
            sliders: BTreeMap::new(),
            inputs: BTreeMap::new(),
            subscriptions: Vec::new(),
            syncing: false,
            scroll: ScrollHandle::new(),
            mapping_input: None,
            hypershift: false,
            group_ix: 0,
        };
        this.prepare_controls(window, cx);
        this
    }

    pub(crate) fn set_page(&mut self, key: &str, _window: &mut Window, cx: &mut Context<Self>) {
        if self.page != key {
            self.page = key.into();
            self.mapping_input = None;
            self.scroll.set_offset(point(px(0.), px(0.)));
            cx.notify();
        }
    }

    pub(crate) fn snapshot(&self) -> Value {
        self.draft.clone()
    }

    pub(crate) fn restore(
        &mut self,
        value: Option<&Value>,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) {
        self.draft = self.spec.profile.clone();
        if let (Some(target), Some(saved)) =
            (self.draft.as_object_mut(), value.and_then(Value::as_object))
        {
            target.extend(
                saved
                    .iter()
                    .map(|(key, value)| (key.clone(), value.clone())),
            );
        }
        self.mapping_input = None;
        self.syncing = true;
        for (path, state) in &self.sliders {
            if path == "smart-preset" {
                let value = self.smart_preset();
                state.update(cx, |state, cx| state.set_value(value as f32, window, cx));
                continue;
            }
            if let Some(value) = self.draft.pointer(path).and_then(Value::as_f64) {
                state.update(cx, |state, cx| state.set_value(value as f32, window, cx));
            }
        }
        for (path, state) in &self.inputs {
            if let Some(value) = self.draft.pointer(path).and_then(Value::as_i64) {
                state.update(cx, |state, cx| {
                    state.set_value(value.to_string(), window, cx)
                });
            }
        }
        self.syncing = false;
        cx.notify();
    }

    fn write(&mut self, path: &str, value: Value, cx: &mut Context<Self>) {
        if self.draft.pointer(path) == Some(&value) {
            return;
        }
        set_pointer(&mut self.draft, path, value);
        cx.emit(MouseProductChanged);
        cx.notify();
    }

    fn write_number(
        &mut self,
        path: &str,
        value: f32,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) {
        set_pointer(&mut self.draft, path, json!(value as i64));
        if path == "/smartTracking/liftOffDistance"
            && self.number("/smartTracking/landingDistance") >= value
        {
            set_pointer(
                &mut self.draft,
                "/smartTracking/landingDistance",
                json!((value - 1.).max(1.) as i64),
            );
        }
        if path == "/smartTracking/landingDistance"
            && self.number("/smartTracking/liftOffDistance") <= value
        {
            set_pointer(
                &mut self.draft,
                "/smartTracking/liftOffDistance",
                json!((value + 1.).min(self.spec.smart_lift_max as f32) as i64),
            );
        }
        if path.starts_with(self.spec.stages_path()) && path.ends_with(self.spec.dpi_axis(0)) {
            if let Some((stage, _)) = path.rsplit_once('/') {
                if !self.boolean(&format!("{stage}/{}", self.spec.independent_key())) {
                    set_pointer(
                        &mut self.draft,
                        &format!("{stage}/{}", self.spec.dpi_axis(1)),
                        json!(value as i64),
                    );
                }
            }
        }
        self.syncing = true;
        for (other_path, slider) in &self.sliders {
            if other_path == path {
                continue;
            }
            if let Some(value) = self.draft.pointer(other_path).and_then(Value::as_f64) {
                if slider.read(cx).value().start() != value as f32 {
                    slider.update(cx, |slider, cx| slider.set_value(value as f32, window, cx));
                    if let Some(input) = self.inputs.get(other_path) {
                        input.update(cx, |input, cx| {
                            input.set_value((value as i64).to_string(), window, cx)
                        });
                    }
                }
            }
        }
        self.syncing = false;
        cx.emit(MouseProductChanged);
        cx.notify();
    }

    fn number(&self, path: &str) -> f32 {
        self.draft
            .pointer(path)
            .and_then(Value::as_f64)
            .unwrap_or(0.) as f32
    }

    fn boolean(&self, path: &str) -> bool {
        self.draft
            .pointer(path)
            .and_then(Value::as_bool)
            .unwrap_or(false)
    }

    fn add_range(
        &mut self,
        path: String,
        min: f32,
        max: f32,
        step: f32,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) {
        let value = self.number(&path);
        let slider = cx.new(|_| {
            SliderState::new()
                .min(min)
                .max(max)
                .step(step)
                .default_value(value)
        });
        let changed_path = path.clone();
        self.subscriptions.push(cx.subscribe_in(
            &slider,
            window,
            move |this, _, event, window, cx| {
                if this.syncing {
                    return;
                }
                let SliderEvent::Change(value) = event else {
                    return;
                };
                let value = value.start().clamp(min, max);
                this.write_number(&changed_path, value, window, cx);
                if let Some(input) = this.inputs.get(&changed_path).cloned() {
                    input.update(cx, |input, cx| {
                        input.set_value((value as i64).to_string(), window, cx)
                    });
                }
            },
        ));
        let input =
            cx.new(|cx| InputState::new(window, cx).default_value((value as i64).to_string()));
        let changed_path = path.clone();
        self.subscriptions.push(cx.subscribe_in(
            &input,
            window,
            move |this, input, event, window, cx| {
                if this.syncing
                    || !matches!(event, InputEvent::Blur | InputEvent::PressEnter { .. })
                {
                    return;
                }
                let Ok(value) = input.read(cx).value().parse::<f32>() else {
                    return;
                };
                let value = ((value / step).ceil() * step).clamp(min, max);
                this.write_number(&changed_path, value, window, cx);
                if let Some(slider) = this.sliders.get(&changed_path).cloned() {
                    this.syncing = true;
                    slider.update(cx, |slider, cx| slider.set_value(value, window, cx));
                    this.syncing = false;
                }
            },
        ));
        self.sliders.insert(path.clone(), slider);
        self.inputs.insert(path, input);
    }

    fn prepare_controls(&mut self, window: &mut Window, cx: &mut Context<Self>) {
        let count = self
            .draft
            .pointer(self.spec.stages_path())
            .and_then(Value::as_array)
            .map_or(0, Vec::len);
        for slot in 0..count {
            for axis in 0..if self.spec.support_xy { 2 } else { 1 } {
                let path = format!(
                    "{}/{slot}/{}",
                    self.spec.stages_path(),
                    self.spec.dpi_axis(axis)
                );
                self.add_range(
                    path,
                    self.spec.min_dpi as f32,
                    self.spec.max_dpi as f32,
                    self.spec.dpi_step as f32,
                    window,
                    cx,
                );
            }
        }
        if self.spec.power_slider || self.spec.performance_power {
            self.add_range(self.spec.power_path().into(), 1., 15., 1., window, cx);
        }
        if self.spec.low_power_slider {
            self.add_range("/lowPowerMode".into(), 5., 100., 5., window, cx);
        }
        if self.spec.low_battery_slider {
            self.add_range("/lowBatteryEffects".into(), 5., 100., 5., window, cx);
        }
        if self.spec.has_page("TAB_LIGHTING") && self.draft.pointer("/brightness/value").is_some() {
            self.add_range("/brightness/value".into(), 0., 100., 1., window, cx);
            self.add_range(
                "/switchOffLighting/idleMinutes".into(),
                1.,
                15.,
                1.,
                window,
                cx,
            );
        }
        if self.spec.calibration.starts_with("smart") {
            self.add_range(
                "/smartTracking/trackingDistance".into(),
                1.,
                3.,
                1.,
                window,
                cx,
            );
            if self.spec.calibration == "smart_only" {
                self.add_range(
                    "/smartTracking/liftOffDistance".into(),
                    2.,
                    self.spec.smart_lift_max as f32,
                    1.,
                    window,
                    cx,
                );
                self.add_range(
                    "/smartTracking/landingDistance".into(),
                    1.,
                    self.spec.smart_landing_max as f32,
                    1.,
                    window,
                    cx,
                );
            } else {
                let slider = cx.new(|_| {
                    SliderState::new()
                        .min(1.)
                        .max(3.)
                        .step(1.)
                        .default_value(self.smart_preset() as f32)
                });
                self.subscriptions.push(cx.subscribe_in(
                    &slider,
                    window,
                    |this, _, event, _, cx| {
                        if this.syncing {
                            return;
                        }
                        if let SliderEvent::Change(value) = event {
                            let (landing, lift) = match value.start().round() as i32 {
                                1 => (1, 2),
                                2 => (1, 3),
                                _ => (2, 3),
                            };
                            let mut tracking = this.draft["smartTracking"].clone();
                            tracking["landingDistance"] = json!(landing);
                            tracking["liftOffDistance"] = json!(lift);
                            this.write("/smartTracking", tracking, cx);
                        }
                    },
                ));
                self.sliders.insert("smart-preset".into(), slider);
            }
        }
        if self.spec.rotation {
            self.add_range("/rotation/value".into(), -44., 44., 1., window, cx);
        }
        if self.spec.has_page("TAB_SCROLLING") {
            for direction in ["upDirection", "downDirection"] {
                self.add_range(
                    format!("/scrollWheelStages/scrollWheelStages/5/{direction}/scrollTension"),
                    0.,
                    100.,
                    1.,
                    window,
                    cx,
                );
                self.add_range(
                    format!("/scrollWheelStages/scrollWheelStages/5/{direction}/scrollSteps"),
                    8.,
                    96.,
                    1.,
                    window,
                    cx,
                );
            }
        }
    }

    fn range(&self, path: &str, label: &str, suffix: &str, enabled: bool, cx: &App) -> AnyElement {
        let Some(slider) = self.sliders.get(path) else {
            return div().into_any_element();
        };
        v_flex()
            .gap_3()
            .w_full()
            .child(
                h_flex()
                    .justify_between()
                    .gap_4()
                    .child(label.to_owned())
                    .child(
                        h_flex()
                            .gap_2()
                            .child(Input::new(&self.inputs[path]).w_20().disabled(!enabled))
                            .child(suffix.to_owned()),
                    ),
            )
            .child(Slider::new(slider).disabled(!enabled))
            .child(
                h_flex()
                    .justify_between()
                    .text_xs()
                    .text_color(cx.theme().muted_foreground)
                    .child(format!("{}", slider.read(cx).min_value()))
                    .child(format!("{}", slider.read(cx).max_value())),
            )
            .into_any_element()
    }

    fn toggle(&self, path: &str, label: &str, cx: &Context<Self>) -> AnyElement {
        let path = path.to_owned();
        Checkbox::new(SharedString::from(format!(
            "mouse-{}-{path}",
            self.spec.product_id
        )))
        .label(label.to_owned())
        .checked(self.boolean(&path))
        .on_click(cx.listener(move |this, checked, window, cx| {
            this.write(&path, json!(*checked), cx);
            if !checked
                && path.starts_with(this.spec.stages_path())
                && path.ends_with(this.spec.independent_key())
            {
                if let Some((stage, _)) = path.rsplit_once('/') {
                    let x_path = format!("{stage}/{}", this.spec.dpi_axis(0));
                    this.write_number(&x_path, this.number(&x_path), window, cx);
                }
            }
        }))
        .into_any_element()
    }

    fn performance(&self, cx: &Context<Self>) -> AnyElement {
        let count = self
            .draft
            .pointer(self.spec.stages_path())
            .and_then(Value::as_array)
            .map_or(0, Vec::len);
        let active = self.number(self.spec.active_path()) as usize;
        let mut sensitivity = surface::panel("灵敏度", cx)
            .child(self.toggle(self.spec.stage_enable_path(), "灵敏度阶段", cx))
            .child(
                h_flex()
                    .flex_wrap()
                    .gap_2()
                    .children((0..count).map(|slot| {
                        let path = self.spec.active_path();
                        Button::new(SharedString::from(format!("mouse-dpi-stage-{slot}")))
                            .label((slot + 1).to_string())
                            .outline()
                            .selected(active == slot + 1)
                            .on_click(cx.listener(move |this, _, _, cx| {
                                this.write(path, json!(slot + 1), cx)
                            }))
                    })),
            );
        let slot = active.saturating_sub(1).min(count.saturating_sub(1));
        if count > 0 {
            let independent_path = format!(
                "{}/{slot}/{}",
                self.spec.stages_path(),
                self.spec.independent_key()
            );
            if self.spec.support_xy {
                sensitivity =
                    sensitivity.child(self.toggle(&independent_path, "启用 X-Y 灵敏度", cx));
            }
            for axis in 0..if self.spec.support_xy && self.boolean(&independent_path) {
                2
            } else {
                1
            } {
                let path = format!(
                    "{}/{slot}/{}",
                    self.spec.stages_path(),
                    self.spec.dpi_axis(axis)
                );
                sensitivity = sensitivity.child(self.range(
                    &path,
                    if self.spec.support_xy {
                        if axis == 0 { "X" } else { "Y" }
                    } else {
                        "DPI"
                    },
                    "DPI",
                    true,
                    cx,
                ));
            }
        }
        let mut right = v_flex().gap_5().child(self.polling(cx));
        if self.spec.performance_power {
            right = right.child(self.power(cx));
        }
        surface::page_columns()
            .child(surface::page_column(sensitivity))
            .child(surface::page_column(right))
            .into_any_element()
    }

    fn polling(&self, cx: &Context<Self>) -> AnyElement {
        let path = self.spec.polling_path();
        let rates = self
            .spec
            .rates
            .get("POLLING_RATE")
            .map(Vec::as_slice)
            .unwrap_or(&[]);
        surface::panel("回报率", cx)
            .child(
                h_flex()
                    .flex_wrap()
                    .gap_2()
                    .children(rates.iter().map(|rate| {
                        let rate = *rate;
                        Button::new(SharedString::from(format!("mouse-polling-{rate}")))
                            .label(format!("{rate} Hz"))
                            .outline()
                            .selected(self.number(path) as u32 == rate)
                            .on_click(
                                cx.listener(move |this, _, _, cx| {
                                    this.write(path, json!(rate), cx)
                                }),
                            )
                    })),
            )
            .into_any_element()
    }

    fn power(&self, cx: &Context<Self>) -> AnyElement {
        let mut panels = v_flex().gap_5();
        if self.spec.power_slider || self.spec.performance_power {
            panels = panels.child(surface::panel("无线省电", cx).child(self.range(
                self.spec.power_path(),
                "闲置后进入睡眠",
                "分钟",
                true,
                cx,
            )));
        }
        if self.spec.low_power_slider {
            panels = panels.child(surface::panel("低功耗模式", cx).child(self.range(
                "/lowPowerMode",
                "电量低于",
                "%",
                true,
                cx,
            )));
        }
        if self.spec.low_battery_slider {
            panels = panels.child(surface::panel("低电量警告", cx).child(self.range(
                "/lowBatteryEffects",
                "电量低于",
                "%",
                true,
                cx,
            )));
        }
        panels.into_any_element()
    }

    fn lighting(&self, cx: &Context<Self>) -> AnyElement {
        let enabled = self.boolean("/brightness/isEnabled");
        surface::page_columns()
            .child(surface::page_column(
                surface::panel("亮度", cx)
                    .child(self.toggle("/brightness/isEnabled", "亮度", cx))
                    .child(self.range("/brightness/value", "亮度", "%", enabled, cx))
                    .child(self.toggle(
                        "/switchOffLighting/isDisplayOn",
                        "显示器关闭时关闭灯光",
                        cx,
                    ))
                    .child(self.toggle("/switchOffLighting/isIdleEnabled", "闲置时关闭灯光", cx))
                    .child(self.range(
                        "/switchOffLighting/idleMinutes",
                        "闲置时间",
                        "分钟",
                        self.boolean("/switchOffLighting/isIdleEnabled"),
                        cx,
                    )),
            ))
            .child(surface::page_column(
                surface::panel("快速效果", cx).child(h_flex().flex_wrap().gap_2().children(
                    self.spec.effects.iter().map(|effect| {
                        let id = effect.id;
                        Button::new(SharedString::from(format!("mouse-effect-{id}")))
                            .label(effect_label(&effect.key).to_owned())
                            .outline()
                            .selected(self.number("/quickEffects/selectedEffectId") as u32 == id)
                            .on_click(cx.listener(move |this, _, _, cx| {
                                this.write("/quickEffects/selectedEffectId", json!(id), cx)
                            }))
                    }),
                )),
            ))
            .into_any_element()
    }

    fn calibration(&self, cx: &Context<Self>) -> AnyElement {
        if self.spec.calibration.starts_with("smart") {
            let asymmetric = self.boolean("/smartTracking/isAsymmetric");
            let mut panel = surface::panel("智能追踪", cx).child(self.toggle(
                "/smartTracking/isAsymmetric",
                "非对称中止",
                cx,
            ));
            if asymmetric && self.spec.calibration == "smart_only" {
                panel = panel
                    .child(self.range("/smartTracking/liftOffDistance", "抬升距离", "", true, cx))
                    .child(self.range("/smartTracking/landingDistance", "着陆距离", "", true, cx));
            } else if asymmetric {
                panel = panel
                    .child(
                        h_flex()
                            .justify_between()
                            .child(format!(
                                "着陆距离：{} mm",
                                self.number("/smartTracking/landingDistance")
                            ))
                            .child(format!(
                                "抬升距离：{} mm",
                                self.number("/smartTracking/liftOffDistance")
                            )),
                    )
                    .child(Slider::new(&self.sliders["smart-preset"]));
            } else {
                panel = panel.child(self.range(
                    "/smartTracking/trackingDistance",
                    "追踪距离",
                    "",
                    true,
                    cx,
                ));
            }
            return surface::page_columns()
                .child(surface::page_column(panel))
                .into_any_element();
        }
        surface::page_columns()
            .child(surface::page_column(
                surface::panel("表面校准", cx).children(
                    self.spec
                        .mats
                        .iter()
                        .filter_map(|mat| mat.get("id").and_then(Value::as_str))
                        .map(|mat| {
                            let mat = mat.to_owned();
                            Button::new(SharedString::from(format!("mouse-surface-{mat}")))
                                .label(mat.replace('_', " "))
                                .outline()
                                .selected(
                                    self.draft
                                        .pointer("/calibration/selectedSurface")
                                        .and_then(Value::as_str)
                                        == Some(mat.as_str()),
                                )
                                .on_click(cx.listener(move |this, _, _, cx| {
                                    this.write("/calibration/selectedSurface", json!(mat), cx)
                                }))
                        }),
                ),
            ))
            .into_any_element()
    }
    fn smart_preset(&self) -> u32 {
        if self.number("/smartTracking/liftOffDistance") == 2. {
            1
        } else if self.number("/smartTracking/landingDistance") == 1. {
            2
        } else {
            3
        }
    }

    fn advanced(&self, cx: &Context<Self>) -> AnyElement {
        let mut panels = surface::page_columns();
        if self.spec.dynamic {
            panels = panels.child(surface::page_column(
                surface::panel("动态灵敏度", cx)
                    .child(
                        Checkbox::new("mouse-dynamic-enabled")
                            .label("动态灵敏度")
                            .checked(self.number("/dynamicSensitivity/state") == 1.)
                            .on_click(cx.listener(|this, value, _, cx| {
                                this.write(
                                    "/dynamicSensitivity/state",
                                    json!(if *value { 1 } else { 0 }),
                                    cx,
                                )
                            })),
                    )
                    .child(
                        h_flex().gap_2().children(
                            ["经典", "自然", "跳跃", "自定义"]
                                .into_iter()
                                .enumerate()
                                .map(|(mode, label)| {
                                    Button::new(SharedString::from(format!("mouse-dynamic-{mode}")))
                                        .label(label)
                                        .outline()
                                        .selected(
                                            self.number("/dynamicSensitivity/mode") as usize
                                                == mode,
                                        )
                                        .on_click(cx.listener(move |this, _, _, cx| {
                                            this.write("/dynamicSensitivity/mode", json!(mode), cx)
                                        }))
                                }),
                        ),
                    ),
            ));
        }
        if self.spec.rotation {
            panels = panels.child(surface::page_column(
                surface::panel("旋转", cx)
                    .child(self.toggle("/rotation/isEnabled", "旋转", cx))
                    .child(self.range(
                        "/rotation/value",
                        "旋转角度",
                        "°",
                        self.boolean("/rotation/isEnabled"),
                        cx,
                    )),
            ));
        }
        panels.into_any_element()
    }

    fn scrolling(&self, cx: &Context<Self>) -> AnyElement {
        let stages = [
            "SW_STANDARD",
            "SW_DISTINCT",
            "SW_ULTRA_FINE",
            "SW_ADAPTIVE",
            "SW_SMOOTH_SCROLL",
            "SW_CUSTOM",
        ];
        let active = self
            .draft
            .pointer("/scrollWheelStages/activeStage")
            .and_then(Value::as_str)
            .unwrap_or("SW_STANDARD");
        let mut panel =
            surface::panel("滚轮阶段", cx).child(h_flex().flex_wrap().gap_2().children(
                stages.into_iter().enumerate().map(|(index, stage)| {
                    Button::new(SharedString::from(format!("mouse-wheel-{stage}")))
                        .label(["标准", "清晰", "超精细", "自适应", "平滑滚动", "自定义"][index])
                        .outline()
                        .selected(active == stage)
                        .on_click(cx.listener(move |this, _, _, cx| {
                            this.write("/scrollWheelStages/activeStage", json!(stage), cx)
                        }))
                }),
            ));
        if active == "SW_CUSTOM" {
            for (direction, label) in [("upDirection", "向上滚动"), ("downDirection", "向下滚动")]
            {
                panel = panel
                    .child(div().child(label))
                    .child(self.range(
                        &format!(
                            "/scrollWheelStages/scrollWheelStages/5/{direction}/scrollTension"
                        ),
                        "滚动张力",
                        "",
                        true,
                        cx,
                    ))
                    .child(self.range(
                        &format!("/scrollWheelStages/scrollWheelStages/5/{direction}/scrollSteps"),
                        "滚动刻度",
                        "",
                        true,
                        cx,
                    ));
            }
        }
        surface::page_columns()
            .child(surface::page_column(panel))
            .into_any_element()
    }

    fn customize(&self, cx: &Context<Self>) -> AnyElement {
        let mut buttons: Vec<&Value> = self
            .spec
            .groups
            .get(self.group_ix)
            .and_then(|group| group["buttonList"].as_array())
            .map(|buttons| buttons.iter().collect())
            .unwrap_or_default();
        if self.spec.groups.is_empty() {
            for button in self.spec.buttons.iter().chain(&self.spec.dkm) {
                if button["inputID"].is_string()
                    && !buttons
                        .iter()
                        .any(|other| other["inputID"] == button["inputID"])
                {
                    buttons.push(button);
                }
            }
        }
        let mut panel = surface::panel("按键自定义", cx)
            .child(
                h_flex()
                    .gap_2()
                    .children(
                        self.spec
                            .groups
                            .iter()
                            .enumerate()
                            .filter_map(|(ix, group)| {
                                let name = group["groupName"].as_str()?.to_owned();
                                Some(
                                    Button::new(SharedString::from(format!("mouse-view-{name}")))
                                        .label(name)
                                        .outline()
                                        .selected(ix == self.group_ix)
                                        .on_click(cx.listener(move |this, _, _, cx| {
                                            this.group_ix = ix;
                                            this.mapping_input = None;
                                            cx.notify();
                                        })),
                                )
                            }),
                    ),
            )
            .children(
                self.spec
                    .image
                    .as_ref()
                    .filter(|_| self.group_ix == 0)
                    .map(|image| {
                        div().w_full().flex().justify_center().child(
                            img(SharedString::from(image.clone()))
                                .w(surface::css(300.))
                                .object_fit(ObjectFit::Contain),
                        )
                    }),
            )
            .child(
                Checkbox::new("mouse-hypershift")
                    .label("Razer Hypershift")
                    .checked(self.hypershift)
                    .on_click(cx.listener(|this, value, _, cx| {
                        this.hypershift = *value;
                        cx.notify();
                    })),
            )
            .children(buttons.iter().filter_map(|button| {
                let input = button["inputID"].as_str()?.to_owned();
                let label = input_label(&input).to_owned();
                Some(
                    Button::new(SharedString::from(format!("mouse-input-{input}")))
                        .label(label)
                        .outline()
                        .disabled(!button["isEnabled"].as_bool().unwrap_or(true))
                        .selected(self.mapping_input.as_ref() == Some(&input))
                        .on_click(cx.listener(move |this, _, _, cx| {
                            this.mapping_input = Some(input.clone());
                            cx.notify();
                        })),
                )
            }));
        if let Some(input) = self.mapping_input.clone() {
            let source_button = buttons
                .iter()
                .find(|button| button["inputID"].as_str() == Some(&input));
            let supported = source_button.is_some_and(|button| {
                button["isEnabled"].as_bool().unwrap_or(true)
                    && button["functionList"].as_array().is_none_or(|functions| {
                        functions
                            .iter()
                            .any(|function| function == "MOUSE_FUNCTION")
                    })
            });
            if supported {
                panel = panel.child(div().font_bold().child(input_label(&input).to_owned()))
                .child(Button::new("mouse-reset-mapping").label("默认").outline().on_click(cx.listener({
                    let input=input.clone();
                    move |this,_,_,cx| {
                        if let Some(mappings)=this.draft["mappings"].as_array_mut() {
                            mappings.retain(|mapping| !(mapping["inputID"] == input && mapping["isHyperShift"].as_bool().unwrap_or(false)==this.hypershift));
                            cx.emit(MouseProductChanged);cx.notify();
                        }
                    }
                })))
                .child(h_flex().gap_2().flex_wrap().children([
                    ("Click", "左键单击"), ("Menu", "右键单击"), ("ScrollButton", "滚轮单击"),
                    ("Previous", "后退"), ("Next", "前进"), ("ScrollUp", "向上滚动"), ("ScrollDown", "向下滚动"),
                ].into_iter().map(|(assignment, label)| {
                    let input = input.clone();
                    let input_type = source_button.and_then(|button| button["inputType"].as_str()).unwrap_or("MouseInput").to_owned();
                    Button::new(SharedString::from(format!("mouse-assignment-{assignment}"))).label(label).outline()
                        .on_click(cx.listener(move |this, _, _, cx| {
                            let entry = json!({"inputID":input,"isHyperShift":this.hypershift,"inputType":input_type,"outputType":"mouseGroup","mouseGroup":{"mouseAssignment":assignment}});
                            let mappings = this.draft.get_mut("mappings").and_then(Value::as_array_mut);
                            if let Some(mappings) = mappings {
                                mappings.retain(|m| !(m["inputID"] == input && m["isHyperShift"].as_bool().unwrap_or(false) == this.hypershift));
                                mappings.push(entry);
                                cx.emit(MouseProductChanged); cx.notify();
                            }
                        }))
                })));
            }
        }
        if self.draft.get("scrollWheel").is_some() {
            panel = panel
                .child(self.toggle("/scrollWheel/smartReelEnabled", "智能滚动", cx))
                .child(self.toggle("/scrollWheel/accelerationEnabled", "滚动加速", cx));
        }
        surface::page_columns()
            .child(surface::page_column(panel))
            .into_any_element()
    }
}

impl Render for MouseProductWorkspace {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        let content = match self.page.as_str() {
            "TAB_PERFORMANCE" => self.performance(cx),
            "TAB_POWER" => self.power(cx),
            "TAB_LIGHTING" => self.lighting(cx),
            "TAB_CALIBRATION" => self.calibration(cx),
            "TAB_SCROLLING" => self.scrolling(cx),
            "ADVANCED" => self.advanced(cx),
            "TAB_PAIRING" => surface::panel("配对", cx)
                .child(surface::note("配对界面尚未接入。", cx))
                .into_any_element(),
            "TAB_CUSTOMIZE" => self.customize(cx),
            _ => surface::panel(crate::i18n::t(&self.page), cx)
                .child(surface::note("此页面的原生控件仍在接入。", cx))
                .into_any_element(),
        };
        div()
            .id("mouse-product-body")
            .size_full()
            .min_h_0()
            .overflow_y_scroll()
            .track_scroll(&self.scroll)
            .child(div().p_5().child(content))
    }
}

fn set_pointer(root: &mut Value, path: &str, value: Value) {
    let parts: Vec<_> = path.trim_start_matches('/').split('/').collect();
    let mut cursor = root;
    for part in &parts[..parts.len().saturating_sub(1)] {
        if cursor.is_array() {
            let Some(next) = part
                .parse::<usize>()
                .ok()
                .and_then(|index| cursor.get_mut(index))
            else {
                return;
            };
            cursor = next;
        } else {
            if !cursor.is_object() {
                *cursor = json!({});
            }
            cursor = cursor
                .as_object_mut()
                .unwrap()
                .entry((*part).to_owned())
                .or_insert_with(|| json!({}));
        }
    }
    if let Some(last) = parts.last() {
        if cursor.is_object() {
            cursor[*last] = value;
        }
    }
}

fn input_label(input: &str) -> &str {
    match input {
        "LeftClick" => "左键单击",
        "RightClick" => "右键单击",
        "ScrollButton" => "滚轮单击",
        "ScrollUp" => "向上滚动",
        "ScrollDown" => "向下滚动",
        "Button4" => "后退",
        "Button5" => "前进",
        "SensitivityStageUp" => "提高灵敏度阶段",
        "SensitivityStageDown" => "降低灵敏度阶段",
        "CycleUpSensitivityStages" => "循环灵敏度阶段",
        "CycleUpProfile" => "循环配置文件",
        _ => input,
    }
}

fn effect_label(effect: &str) -> &str {
    match effect {
        "Audio_Meter_Effect" => "音频指示器",
        "Breathing_Effect" => "呼吸",
        "Reactive_Effect" => "响应",
        "Spectrum_Effect" => "光谱循环",
        "Static_Effect" => "静态",
        "Tidal_Effect" => "潮汐",
        "Wave_Effect" => "波浪",
        "Wheel_Effect" => "旋转",
        "Fire_Effect" => "火焰",
        "Starlight_Effect" => "星光",
        _ => effect,
    }
}
