[package]
name="razer-tray"
version.workspace=true
edition.workspace=true

[dependencies]
razer-model.workspace = true
anyhow.workspace=true
gpui-kit.workspace=true
tray-icon.workspace=true
async-channel.workspace=true
serde_json.workspace=true
razer-i18n.workspace=true
razer-widgets.workspace=true

[target.'cfg(windows)'.dependencies]
raw-window-handle.workspace=true
windows-sys={workspace=true,features=["Win32_Foundation","Win32_Graphics_Gdi","Win32_Security","Win32_System_Threading","Win32_System_JobObjects","Win32_UI_WindowsAndMessaging"]}

[dev-dependencies]
gpui-kit={workspace=true,features=["test-support"]}
