// Original 182 main module 6114 (also used by MapKeyboard); stable input IDs.
&[
    ("alphanumeric", "KEY_A", "A"),
    ("alphanumeric", "KEY_B", "B"),
    ("alphanumeric", "KEY_C", "C"),
    ("alphanumeric", "KEY_D", "D"),
    ("alphanumeric", "KEY_E", "E"),
    ("alphanumeric", "KEY_F", "F"),
    ("alphanumeric", "KEY_G", "G"),
    ("alphanumeric", "KEY_H", "H"),
    ("alphanumeric", "KEY_I", "I"),
    ("alphanumeric", "KEY_J", "J"),
    ("alphanumeric", "KEY_K", "K"),
    ("alphanumeric", "KEY_L", "L"),
    ("alphanumeric", "KEY_M", "M"),
    ("alphanumeric", "KEY_N", "N"),
    ("alphanumeric", "KEY_O", "O"),
    ("alphanumeric", "KEY_P", "P"),
    ("alphanumeric", "KEY_Q", "Q"),
    ("alphanumeric", "KEY_R", "R"),
    ("alphanumeric", "KEY_S", "S"),
    ("alphanumeric", "KEY_T", "T"),
    ("alphanumeric", "KEY_U", "U"),
    ("alphanumeric", "KEY_V", "V"),
    ("alphanumeric", "KEY_W", "W"),
    ("alphanumeric", "KEY_X", "X"),
    ("alphanumeric", "KEY_Y", "Y"),
    ("alphanumeric", "KEY_Z", "Z"),
    ("alphanumeric", "KEY_0", "0"),
    ("alphanumeric", "KEY_1", "1"),
    ("alphanumeric", "KEY_2", "2"),
    ("alphanumeric", "KEY_3", "3"),
    ("alphanumeric", "KEY_4", "4"),
    ("alphanumeric", "KEY_5", "5"),
    ("alphanumeric", "KEY_6", "6"),
    ("alphanumeric", "KEY_7", "7"),
    ("alphanumeric", "KEY_8", "8"),
    ("alphanumeric", "KEY_9", "9"),
    ("function", "KEY_F1", "F1"),
    ("function", "KEY_F2", "F2"),
    ("function", "KEY_F3", "F3"),
    ("function", "KEY_F4", "F4"),
    ("function", "KEY_F5", "F5"),
    ("function", "KEY_F6", "F6"),
    ("function", "KEY_F7", "F7"),
    ("function", "KEY_F8", "F8"),
    ("function", "KEY_F9", "F9"),
    ("function", "KEY_F10", "F10"),
    ("function", "KEY_F11", "F11"),
    ("function", "KEY_F12", "F12"),
    ("function", "KEY_F13", "F13"),
    ("function", "KEY_F14", "F14"),
    ("function", "KEY_F15", "F15"),
    ("function", "KEY_F16", "F16"),
    ("function", "KEY_F17", "F17"),
    ("function", "KEY_F18", "F18"),
    ("function", "KEY_F19", "F19"),
    ("function", "KEY_F20", "F20"),
    ("function", "KEY_F21", "F21"),
    ("function", "KEY_F22", "F22"),
    ("function", "KEY_F23", "F23"),
    ("function", "KEY_F24", "F24"),
    ("numpad", "KEY_NUMPAD_NUM_LOCK", "Num Lock"),
    ("numpad", "KEY_NUMPAD_0", "Num 0"),
    ("numpad", "KEY_NUMPAD_1", "Num 1"),
    ("numpad", "KEY_NUMPAD_2", "Num 2"),
    ("numpad", "KEY_NUMPAD_3", "Num 3"),
    ("numpad", "KEY_NUMPAD_4", "Num 4"),
    ("numpad", "KEY_NUMPAD_5", "Num 5"),
    ("numpad", "KEY_NUMPAD_6", "Num 6"),
    ("numpad", "KEY_NUMPAD_7", "Num 7"),
    ("numpad", "KEY_NUMPAD_8", "Num 8"),
    ("numpad", "KEY_NUMPAD_9", "Num 9"),
    ("numpad", "KEY_NUMPAD_SLASH", "Num /"),
    ("numpad", "KEY_NUMPAD_ASTERISK", "Num *"),
    ("numpad", "KEY_NUMPAD_DASH", "Num -"),
    ("numpad", "KEY_NUMPAD_PLUS", "Num +"),
    ("numpad", "KEY_NUMPAD_PERIOD", "Num ."),
    ("numpad", "KEY_NUMPAD_ENTER", "Num Enter"),
    ("navigation", "KEY_UP_ARROW", "Up"),
    ("navigation", "KEY_DOWN_ARROW", "Down"),
    ("navigation", "KEY_LEFT_ARROW", "Left"),
    ("navigation", "KEY_RIGHT_ARROW", "Right"),
    ("navigation", "KEY_PAGE_UP", "Page Up"),
    ("navigation", "KEY_PAGE_DOWN", "Page Down"),
    ("navigation", "KEY_BACKSPACE", "Backspace"),
    ("navigation", "KEY_TAB", "Tab"),
    ("navigation", "KEY_SPACEBAR", "Space"),
    ("navigation", "KEY_ENTER", "Enter"),
    ("navigation", "KEY_ESC", "Esc"),
    ("navigation", "KEY_INSERT", "Insert"),
    ("navigation", "KEY_HOME", "Home"),
    ("navigation", "KEY_DELETE", "Delete"),
    ("navigation", "KEY_END", "End"),
    ("navigation", "KEY_PRINT_SCREEN", "Print Screen"),
    ("navigation", "KEY_PAUSE", "Pause"),
    ("navigation", "KEY_APPLICATION", "Menu"),
    ("modifiers", "KEY_LEFT_CTRL", "Ctrl"),
    ("modifiers", "KEY_RIGHT_CTRL", "Right Ctrl"),
    ("modifiers", "KEY_LEFT_SHIFT", "Shift"),
    ("modifiers", "KEY_RIGHT_SHIFT", "Right Shift"),
    ("modifiers", "KEY_LEFT_ALT", "Alt"),
    ("modifiers", "KEY_RIGHT_ALT", "Right Alt"),
    ("modifiers", "KEY_LEFT_GUI", "Windows"),
    ("modifiers", "KEY_CAPS_LOCK", "Caps Lock"),
    ("modifiers", "KEY_SCROLL_LOCK", "Scroll Lock"),
    ("modifiers", "KEY_NUMPAD_NUM_LOCK", "Num Lock"),
    ("symbols", "KEY_TILDE", "`"),
    ("symbols", "KEY_NON_US_POUND", "#"),
    ("symbols", "KEY_HYPEN", "-"),
    ("symbols", "KEY_EQUAL", "="),
    ("symbols", "KEY_OPEN_SQUARE_BRACKET", "["),
    ("symbols", "KEY_CLOSE_SQUARE_BRACKET", "]"),
    ("symbols", "KEY_BACKSLASH", "\\"),
    ("symbols", "KEY_SEMICOLON", ";"),
    ("symbols", "KEY_APOSTROPHE", "'"),
    ("symbols", "KEY_COMMA", ","),
    ("symbols", "KEY_PERIOD", "."),
    ("symbols", "KEY_SLASH", "/"),
    // Source module 6114 leaves type empty for these layout-specific inputs.
    // They remain valid when a saved/recorded physical input uses the ID.
    ("record", "KEY_CANCEL", "Cancel"),
    ("record", "KEY_YEN", "¥"),
    ("record", "KEY_RO", "Ro"),
    ("record", "KEY_MUHENKAN", "Muhenkan"),
    ("record", "KEY_HENKAN", "Henkan"),
    ("record", "KEY_KATAKANA_HIRAGANA", "Katakana / Hiragana"),
    ("record", "KEY_NON_US_BACKSLASH", "Non-US \\"),
]
