[package]
name = "razer-shell"
version.workspace = true
edition.workspace = true

[dependencies]
razer-dashboard.workspace = true
razer-discovery.workspace = true
razer-settings.workspace = true
razer-tray.workspace = true
razer-ipc.workspace = true
razer-platform.workspace = true
razer-app-pages.workspace = true
razer-i18n.workspace = true
razer-device.workspace = true
razer-widgets.workspace = true
razer-state.workspace = true
gpui-kit.workspace = true
anyhow.workspace = true
tray-icon.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_ignored.workspace = true
uuid.workspace = true
razer-assets.workspace = true
razer-catalog.workspace = true
razer-model.workspace = true
razer-storage.workspace = true
razer-pages.workspace = true

[target.'cfg(windows)'.dependencies]
raw-window-handle.workspace = true
windows-sys = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_System_Threading",
  "Win32_System_JobObjects",
  "Win32_Security",
  "Win32_UI_WindowsAndMessaging",
] }


[dev-dependencies]
gpui-kit = { workspace = true, features = ["test-support"] }
