"""Prepare current 1383 Banner resources; never run vendor code."""
import base64
import hashlib
import io
import json
import sys
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
check = sys.argv[1:] == ['--check']
if sys.argv[1:] not in ([], ['--check']):
    raise ValueError('Unknown argument')
receipt = json.loads((ROOT / 'docs/re/audio-oled-banner-current-evidence.json').read_text(encoding='utf-8'))
records = []
cache = {}
digest = lambda data: hashlib.sha256(data).hexdigest()

def verify(item):
    origin = item['receipt']
    if origin['path'] not in cache:
        source = (ROOT / origin['path']).read_bytes()
        cache[origin['path']] = (digest(source), source.decode('utf-8').encode('utf-16-le'))
    source_hash, utf16 = cache[origin['path']]
    assert source_hash == origin['sha256']
    assert utf16[origin['offset'] * 2:origin['end'] * 2].decode('utf-16-le') == origin['source']

def emit(path, data):
    if check:
        assert path.read_bytes() == data, f'Stale {path}'
    else:
        path.write_bytes(data)

for item in receipt['assets']:
    verify(item)
    assert item['src'].startswith('data:image/png;base64,') and item['src'] in item['receipt']['source']
    raw = base64.b64decode(item['src'].split(',', 1)[1], validate=True)
    with Image.open(io.BytesIO(raw)) as source:
        rgba = source.convert('RGBA')
        gray = rgba.convert('RGB').convert('L', (0.2126, 0.7152, 0.0722, 0)).convert('RGBA')
        gray.putalpha(rgba.getchannel('A'))
        assert source.size == (232, 20)
        output = io.BytesIO()
        gray.save(output, format='PNG')
    encoded = output.getvalue()
    emit(ROOT / 'assets' / item['output'], encoded)
    records.append({'id':item['id'], 'source':item['receipt']['path'], 'source_sha256':item['receipt']['sha256'],
                    'inline_sha256':digest(raw), 'output':'assets/' + item['output'], 'output_sha256':digest(encoded),
                    'width':232, 'height':20, 'transform':'Source CSS grayscale(100%), source alpha retained'})
for item in receipt['icons']:
    verify(item)
    encoded = item['svg'].encode('utf-8')
    emit(ROOT / 'assets' / item['output'], encoded)
    records.append({'id':item['id'], 'source':item['receipt']['path'], 'source_sha256':item['receipt']['sha256'],
                    'output':'assets/' + item['output'], 'output_sha256':digest(encoded),
                    'transform':'Literal React SVG tree serialization'})
emit(ROOT / 'assets/synapse/audio-oled-banner-assets.json', (json.dumps(records, indent=2) + '\n').encode())
rows = '\n'.join(f'    ("{r["output"].removeprefix("assets/")}", include_bytes!("{Path(r["output"]).name}")),' for r in records)
emit(ROOT / 'assets/synapse/audio-oled-banner-embedded.rs', ('// Generated by tools/prepare-audio-oled-banner-assets.py\n&[\n' + rows + '\n]\n').encode())
print(f'1383 Banner: {len(records)} current resources; image pixels and literal SVG bytes validated.')
