"""Prepare declared 1383 System Info SVGs/inline dots; never execute vendor JS."""
import base64
import hashlib
import json
import sys
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path
from urllib.request import urlopen

ROOT=Path(__file__).resolve().parents[1]
BASE=ROOT/'.ref/devices/1383'
digest=lambda b:hashlib.sha256(b).hexdigest()
flags=sys.argv[1:]
if flags not in ([],['--check']): raise ValueError('Unknown argument')
check=bool(flags)
receipt=json.loads((ROOT/'docs/re/audio-oled-system-source.json').read_text(encoding='utf8'))
manifest=json.loads((BASE/'asset-manifest.json').read_text(encoding='utf8'))['files']
declared={v[v.index('static/'):]:v for v in manifest.values() if 'static/' in v}
def write(target,data):
    if check: assert target.read_bytes()==data,f'Stale {target}'
    else: target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(data)
def verify(item):
    r=item['receipt'];raw=(ROOT/r['path']).read_bytes()
    assert digest(raw)==r['sha256']
    units=raw.decode('utf8').encode('utf-16-le')
    assert units[2*r['offset']:2*r['end']].decode('utf-16-le')==r['source']
records=[]
for item in receipt['assets']:
    verify(item);src=item['src'];inline=src.startswith('data:')
    if inline:
        assert src in item['receipt']['source']
        data=base64.b64decode(src.split(',',1)[1],validate=True)
        source=ROOT/item['receipt']['path']
    else:
        assert src in declared and src.startswith('static/media/')
        source=(BASE/src).resolve();assert source.is_relative_to(BASE.resolve())
        if not source.exists():
            assert not check,f'Missing source {src}'
            with urlopen('https://apps.razer.com'+declared[src],timeout=30) as response:
                data=response.read();source.parent.mkdir(parents=True,exist_ok=True);source.write_bytes(data)
                source.with_suffix(source.suffix+'.http.json').write_text(json.dumps({'url':response.url,'sha256':digest(data),'fetched_at_utc':datetime.now(timezone.utc).isoformat()},indent=2)+'\n',encoding='utf8')
        data=source.read_bytes()
    out=ROOT/'assets'/item['output'];write(out,data)
    record={'id':item['id'],'source':source.relative_to(ROOT).as_posix(),'source_sha256':digest(source.read_bytes()),'output':out.relative_to(ROOT).as_posix(),'output_sha256':digest(data),'method':'Original source bytes'}
    if inline:
        assert data[:8]==b'\x89PNG\r\n\x1a\n';w=int.from_bytes(data[16:20],'big');h=int.from_bytes(data[20:24],'big');assert(w,h)==(6,6)
        record.update(inline_sha256=digest(data),width=w,height=h)
    else:
        root=ET.fromstring(data);assert root.tag.endswith('svg');record.update(viewBox=root.attrib.get('viewBox'),width=root.attrib.get('width'),height=root.attrib.get('height'))
    records.append(record)
for item in receipt['icons']:
    verify(item);data=item['svg'].encode();ET.fromstring(data);out=ROOT/'assets'/item['output'];write(out,data)
    records.append({'id':item['id'],'source':item['receipt']['path'],'source_sha256':item['receipt']['sha256'],'output':out.relative_to(ROOT).as_posix(),'output_sha256':digest(data),'method':'Static literal React SVG serialization'})
write(ROOT/'assets/synapse/audio-oled-system-assets.json',(json.dumps(records,indent=2)+'\n').encode())
entries='\n'.join(f'    ("{r["output"].removeprefix("assets/")}", include_bytes!("{Path(r["output"]).name}")),' for r in records)
write(ROOT/'assets/synapse/audio-oled-system-embedded.rs',('// Generated by tools/prepare-audio-oled-system-assets.py\n&[\n'+entries+'\n]\n').encode())
sizes={r['output'].removeprefix('assets/'):[float(r['width']),float(r['height'])] for r in records if r['id'].startswith('tag-')}
write(ROOT/'src/features/audio_oled_system_asset_sizes.json',(json.dumps({'sizes':sizes},indent=2)+'\n').encode())
print(f'1383 System Info: {len(records)} source assets statically validated.')
