"""Prepare current tray SVG literals and manifest-declared battery artwork.

Vendor JS is read as text, never evaluated. --check performs no network I/O.
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
import xml.etree.ElementTree as ET
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / '.ref/applications/systray/systrayv2'
JS = BASE / 'static/js/492.2b959cf3.chunk.js'
ASSETS = ROOT / 'assets/synapse'
CHECK = '--check' in sys.argv
NS = 'http://www.w3.org/2000/svg'
ET.register_namespace('', NS)


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def emit(path: Path, data: bytes) -> None:
    if CHECK:
        assert path.read_bytes() == data, f'Stale {path}'
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)


source = JS.read_text(encoding='utf8')
start = source.index('const u=[') + len('const u=')
end = source.index('];var v=a(2722)', start) + 1
literal = source[start:end]
pattern = r'\{name:"([^"]+)",d:"([^"]+)",transformX:([\d.-]+),transformY:([\d.-]+)\}'
icons = list(re.finditer(pattern, literal))
assert len(icons) == literal.count('{name:'), 'Unhandled icon literal'
records = []
for icon in icons:
    name, path, tx, ty = icon.groups()
    # M() has no className or margin; f() supplies width=height=40.
    svg = (f'<svg xmlns="{NS}" width="40" height="40" fill="#ccc" '
           'viewBox="0 0 26.666666666666668 26.666666666666668">'
           f'<g transform="translate(0 0)"><path d="{path}" '
           f'transform="translate({tx} {ty})"/></g></svg>\n').encode()
    ET.fromstring(svg)
    output = ASSETS / f'tray-widget-category-{name.lower()}.svg'
    emit(output, svg)
    records.append({'category': name, 'source': JS.relative_to(ROOT).as_posix(),
                    'source_sha256': sha(JS.read_bytes()),
                    'literal_start': start + icon.start(), 'literal_end': start + icon.end(),
                    'output': output.relative_to(ROOT).as_posix(),
                    'output_sha256': sha(svg), 'method': 'Static u literal + M SVG serialization'})

manifest = json.loads((BASE / 'asset-manifest.json').read_text(encoding='utf8'))['files']
names = [f'battery-{level}' for level in range(0, 101, 10)]
names += ['battery-charging', 'battery-charging-100', 'battery-paused', 'icon_device_off']


def fetch(name: str) -> tuple[str, Path, bytes]:
    declared = manifest[f'static/media/{name}.svg']
    source_path = BASE / declared.removeprefix('./')
    assert source_path.resolve().is_relative_to(BASE.resolve())
    if not source_path.exists():
        assert not CHECK, f'Missing current manifest asset {source_path}'
        with urlopen('https://apps.razer.com/systray/systrayv2/' + declared.removeprefix('./'), timeout=30) as reply:
            raw = reply.read()
        source_path.parent.mkdir(parents=True, exist_ok=True)
        source_path.write_bytes(raw)
    raw = source_path.read_bytes()
    ET.fromstring(raw)
    return name, source_path, raw


with ThreadPoolExecutor(max_workers=6) as workers:
    media = list(workers.map(fetch, names))
for name, source_path, raw in media:
    if name == 'battery-paused':
        parsed = ET.fromstring(raw)
        views = parsed.findall(f'{{{NS}}}view')
        assert len(views) == 11
        for view in views:
            level, box = view.attrib['id'], view.attrib['viewBox']
            cropped = ET.fromstring(raw)
            cropped.set('viewBox', box)
            cropped.set('width', '20')
            cropped.set('height', '20')
            output = ASSETS / f'tray-widget-battery-paused-{level}.svg'
            result = ET.tostring(cropped, encoding='utf8') + b'\n'
            emit(output, result)
            records.append({'source': source_path.relative_to(ROOT).as_posix(),
                            'source_sha256': sha(raw), 'output': output.relative_to(ROOT).as_posix(),
                            'output_sha256': sha(result), 'method': f'Source view fragment #{level}', 'viewBox': box})
    else:
        output = ASSETS / f'tray-widget-{name.replace("icon_device_off", "battery-off")}.svg'
        emit(output, raw)
        records.append({'source': source_path.relative_to(ROOT).as_posix(),
                        'source_sha256': sha(raw), 'output': output.relative_to(ROOT).as_posix(),
                        'output_sha256': sha(raw), 'method': 'Original current manifest SVG bytes'})
emit(ASSETS / 'tray-widget-assets.json', (json.dumps(records, indent=2) + '\n').encode())
entries = '\n'.join(f'    ("{record["output"].removeprefix("assets/")}", include_bytes!("{Path(record["output"]).name}")),' for record in records)
emit(ASSETS / 'tray-widget-embedded.rs', ('// Generated by tools/prepare-tray-widget-assets.py\n&[\n' + entries + '\n]\n').encode())
print(f'Current tray: {len(icons)} category SVGs, {len(records) - len(icons)} battery SVGs prepared/validated.')
print('Source category names: ' + ', '.join(icon.group(1) for icon in icons))
