"""Prepare exact current Armory product artwork; downloaded JavaScript is data.

Run the current Armory root audits first. The per-product Webpack request,
module export and source hash are checked before converting a prd-3x image.
The dedicated lookup table prevents ordinary base-resource preparation from
discarding these additional product identities.
"""
from pathlib import Path
import hashlib
import io
import json
import sys

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
CHECK = '--check' in sys.argv
EVIDENCE = (
    'docs/re/armory-product-roots-current-evidence.json',
    'docs/re/armory-audio-roots-current-evidence.json',
    'docs/re/armory-audio-next-roots-current-evidence.json',
)


def digest(data):
    return hashlib.sha256(data).hexdigest()


def emit(path, data):
    if isinstance(data, str):
        data = data.encode('utf-8')
    if CHECK:
        if path.read_bytes() != data:
            raise ValueError(f'Stale prepared resource: {path}')
    else:
        path.write_bytes(data)


records, identities = [], {}
for evidence in EVIDENCE:
    for product in json.loads((ROOT / evidence).read_text(encoding='utf-8'))['products']:
        pid = product['product_id']
        source = (ROOT / product['source']).read_text(encoding='utf-8')
        if digest(source.encode()) != product['sha256']:
            raise ValueError(f'Changed source for {pid}')
        manifest_path = ROOT / f'.ref/devices/{pid}/asset-manifest.json'
        manifest = json.loads(manifest_path.read_text(encoding='utf-8'))
        declared = {f'.ref/devices/{pid}/' + path.removeprefix('./')
                    for path in manifest['files'].values()}
        for item in product['images']:
            if not item['request'].endswith('/img_prods/prd-3x.png'):
                continue
            module_path = item['module_source']
            module = (ROOT / module_path).read_bytes()
            if module_path not in declared or digest(module) != item['module_sha256']:
                raise ValueError(f'Changed image export for {pid}')
            request = f'"{item["request"]}":[{item["module_id"]},'
            if source[item['context_offset']:].find(request) != 0:
                raise ValueError(f'Changed image request for {pid}')
            media = ROOT / item['local']
            raw = media.read_bytes()
            name = f'product-{pid}-{media.stem}.png'
            output = f'assets/synapse/{name}'
            with Image.open(io.BytesIO(raw)) as original:
                image = original.convert('RGBA')
                encoded = io.BytesIO()
                image.save(encoded, format='PNG', optimize=True)
                png = encoded.getvalue()
                width, height = image.size
            emit(ROOT / output, png)
            record = {
                'source': item['local'], 'output': output,
                'source_sha256': digest(raw), 'sha256': digest(png),
                'width': width, 'height': height, 'mode': 'RGBA',
                'source_url': item['url'], 'source_kind': 'downloaded_static_asset',
                'evidence': evidence, 'product_id': pid, 'edition_id': item['edition_id'],
                'webpack_request': item['request'], 'webpack_module': item['module_id'],
                'context': product['source'], 'context_sha256': product['sha256'],
                'module_source': module_path, 'module_sha256': item['module_sha256'],
                'manifest_sha256': digest(manifest_path.read_bytes()),
                'conversion': 'Pillow AVIF decoder to RGBA PNG, original dimensions retained',
            }
            if not any(entry['output'] == output for entry in records):
                records.append(record)
            identity, asset = (pid, item['edition_id']), output.removeprefix('assets/')
            if identity in identities and identities[identity] != asset:
                raise ValueError(f'Conflicting exact image identity: {identity}')
            identities[identity] = asset

emit(ROOT / 'assets/synapse/armory-product-images.rs',
     '// Generated by tools/prepare-armory-product-images.py from current Webpack requests.\n&[\n'
     + ''.join(f'    ({pid}, {edition}, 0, DeviceImage::Product, "{asset}"),\n'
               for (pid, edition), asset in sorted(identities.items())) + ']\n')
dashboard_identities = []
for pid, edition in sorted(identities):
    source = f'assets/synapse/dashboard-{pid}-{edition}-0-source.avif'
    raw = (ROOT / source).read_bytes()
    receipt_path = source + '.http.json'
    receipt = json.loads((ROOT / receipt_path).read_text(encoding='utf-8'))
    url = (f'https://apps.razer.com/synapse/products/{pid}/ui/{pid}_{edition}/PluginImages/'
           f'{pid}_{edition}_0_dashboard3x.avif')
    if receipt['source_url'] != url or receipt['sha256'] != digest(raw):
        raise ValueError(f'Invalid exact Dashboard image receipt: {pid}:{edition}')
    output = f'assets/synapse/armory-dashboard-{pid}-{edition}.png'
    with Image.open(io.BytesIO(raw)) as original:
        image = original.convert('RGBA')
        encoded = io.BytesIO()
        image.save(encoded, format='PNG', optimize=True)
        png = encoded.getvalue()
        width, height = image.size
    emit(ROOT / output, png)
    records.append({
        'source': source, 'output': output,
        'source_sha256': digest(raw), 'sha256': digest(png),
        'width': width, 'height': height, 'mode': 'RGBA',
        'source_url': url, 'source_kind': 'downloaded_static_asset',
        'evidence': receipt_path, 'product_id': pid, 'edition_id': edition,
        'purpose': 'Dashboard and app-picker PluginImages artwork, distinct from Armory prd artwork',
        'conversion': 'Pillow AVIF decoder to RGBA PNG, original dimensions retained',
    })
    dashboard_identities.append((pid, edition, output.removeprefix('assets/')))
emit(ROOT / 'assets/synapse/armory-dashboard-images.rs',
     '// Generated by tools/prepare-armory-product-images.py from original PluginImages URLs.\n&[\n'
     + ''.join(f'    ({pid}, {edition}, 0, "{asset}"),\n'
               for pid, edition, asset in dashboard_identities) + ']\n')
emit(ROOT / 'docs/re/armory-product-image-resources.json', json.dumps({
    'method': 'Static current-source Webpack identity and SHA validation, offline AVIF-to-PNG conversion.',
    'records': records,
    'identities': [{'product_id': pid, 'edition_id': edition, 'asset': asset}
                   for (pid, edition), asset in sorted(identities.items())],
    'dashboard_identities': [{'product_id': pid, 'edition_id': edition, 'asset': asset}
                             for pid, edition, asset in dashboard_identities],
}, ensure_ascii=False, indent=2) + '\n')

manifest_path = ROOT / 'assets/synapse/manifest.json'
manifest = json.loads(manifest_path.read_text(encoding='utf-8'))
embedded_path = ROOT / 'assets/synapse/embedded.rs'
embedded = embedded_path.read_text(encoding='utf-8')
for record in records:
    target = record['output']
    existing = next((entry for entry in manifest['entries'] if entry['output'] == target), None)
    asset = target.removeprefix('assets/')
    if CHECK:
        if existing != record or f'"{asset}"' not in embedded:
            raise ValueError(f'Missing exact current resource registration: {target}')
    else:
        if existing:
            existing.clear()
            existing.update(record)
        else:
            manifest['entries'].append(record)
        if f'"{asset}"' not in embedded:
            embedded = embedded.rstrip().removesuffix(']') + (
                f'    ("{asset}", include_bytes!("{Path(target).name}") as &[u8]),\n]\n')
if not CHECK:
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    embedded_path.write_text(embedded, encoding='utf-8')
print(f'Armory product artwork: {len(records)} exact images, {len(identities)} product/edition identities verified.')
