"""Fetch only manifest-declared current systray artwork; never run vendor code."""
import hashlib
import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / '.ref/applications/systray/systrayv2'
check = '--check' in sys.argv
manifest = json.loads((BASE / 'asset-manifest.json').read_text(encoding='utf8'))['files']
digest = lambda b: hashlib.sha256(b).hexdigest()
records = []
def write(path, data):
    if check:
        assert path.read_bytes() == data, f'Stale {path}'
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
for name in ['guest', 'user']:
    declared = manifest[f'static/media/{name}.svg']
    source = BASE / declared.removeprefix('./')
    assert source.resolve().is_relative_to(BASE.resolve())
    if not source.exists():
        assert not check, f'Missing {source}'
        with urlopen('https://apps.razer.com/systray/systrayv2/' + declared.removeprefix('./'), timeout=30) as reply:
            raw = reply.read()
        source.parent.mkdir(parents=True, exist_ok=True)
        source.write_bytes(raw)
    raw = source.read_bytes()
    ET.fromstring(raw)
    output = ROOT / f'assets/synapse/tray-{name}-current.svg'
    write(output, raw)
    records.append({'source':source.relative_to(ROOT).as_posix(),'source_sha256':digest(raw),'output':output.relative_to(ROOT).as_posix(),'output_sha256':digest(raw),'method':'Original source bytes'})
evidence = json.loads((ROOT / 'docs/re/tray-account-current-evidence.json').read_text(encoding='utf8'))
gear = ROOT / evidence['gear']['path']
assert digest(gear.read_bytes()) == evidence['gear']['sha256']
ET.fromstring(gear.read_bytes())
records.append({'source':evidence['js']['path'],'source_sha256':evidence['js']['sha256'],'output':gear.relative_to(ROOT).as_posix(),'output_sha256':digest(gear.read_bytes()),'method':'Static literal React SVG serialization; ce AST slice'})
write(ROOT / 'assets/synapse/tray-account-assets.json', (json.dumps(records,indent=2)+'\n').encode())
entries='\n'.join(f'    ("{r["output"].removeprefix("assets/")}", include_bytes!("{Path(r["output"]).name}")),' for r in records)
write(ROOT / 'assets/synapse/tray-account-embedded.rs', ('// Generated by tools/prepare-tray-account-assets.py\n&[\n'+entries+'\n]\n').encode())
print('Current tray: 3 source SVGs validated.')
