"""Prepare the current 1383 emotes and literal artwork icons without vendor code."""
import base64
from concurrent.futures import ThreadPoolExecutor
import hashlib
import io
import json
from pathlib import Path
import sys
from urllib.request import urlopen
from PIL import Image, ImageSequence

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / '.ref/devices/1383'
check = sys.argv[1:] == ['--check']
if sys.argv[1:] not in ([], ['--check']):
    raise ValueError('Unknown argument')
sha = lambda data: hashlib.sha256(data).hexdigest()
evidence = json.loads((ROOT / 'docs/re/audio-oled-artwork-current-evidence.json').read_text(encoding='utf8'))
manifest = json.loads((BASE / 'asset-manifest.json').read_text(encoding='utf8'))['files']
declared = {value[value.index('static/'):]: value for value in manifest.values() if 'static/' in value}


def verify(item):
    data = (ROOT / item['path']).read_bytes()
    assert sha(data) == item['sha256']
    assert data.decode().encode('utf-16-le')[item['offset'] * 2:item['end'] * 2].decode('utf-16-le') == item['source']


def emit(path, data):
    if check:
        assert path.read_bytes() == data, f'Stale {path}'
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)


def prepare(item):
    verify(item['receipt'])
    verify(item['loader'])
    src = item['src']
    if src.startswith('data:image/'):
        content = base64.b64decode(src.split(',', 1)[1], validate=True)
        source = item['receipt']['path']
        source_sha = item['receipt']['sha256']
    else:
        assert src in declared and src.startswith('static/media/')
        target = (BASE / src).resolve()
        assert target.is_relative_to(BASE.resolve())
        if not target.exists():
            assert not check, f'Missing {src}'
            with urlopen('https://apps.razer.com' + declared[src], timeout=30) as response:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(response.read())
        content = target.read_bytes()
        source = target.relative_to(ROOT).as_posix()
        source_sha = sha(content)
    with Image.open(io.BytesIO(content)) as image:
        frames, durations = [], []
        for frame in ImageSequence.Iterator(image):
            # Emote source assets are already grayscale; preserve their exact
            # displayed RGBA rather than inventing another palette transform.
            frames.append(frame.convert('RGBA'))
            durations.append(frame.info.get('duration', 0))
        output = io.BytesIO()
        animated = len(frames) > 1
        frames[0].save(output, format='WEBP', save_all=animated,
                       append_images=frames[1:] if animated else [],
                       duration=durations if animated else 0,
                       loop=image.info.get('loop', 0), lossless=True, method=6)
        prepared = output.getvalue()
        with Image.open(io.BytesIO(prepared)) as native:
            elapsed, source_index, end = 0, 0, durations[0]
            for frame in ImageSequence.Iterator(native):
                frame.load()
                if animated:
                    while elapsed >= end:
                        source_index += 1
                        end += durations[source_index]
                assert frame.convert('RGBA').tobytes() == frames[source_index].tobytes()
                elapsed += frame.info.get('duration', 0)
            if animated:
                assert elapsed == sum(durations)
        emit(ROOT / 'assets' / item['output'], prepared)
        return {'id': item['id'], 'source': source, 'source_sha256': source_sha,
                'output': 'assets/' + item['output'], 'output_sha256': sha(prepared),
                'width': image.width, 'height': image.height,
                'source_frame_durations_ms': durations, 'loop': image.info.get('loop', 0),
                'source_kind': 'current_literal_emote', 'inline_sha256': sha(content)}


with ThreadPoolExecutor(max_workers=8) as executor:
    records = list(executor.map(prepare, evidence['assets']))
for icon in evidence['icons']:
    verify(icon['receipt'])
    data = icon['svg'].encode()
    emit(ROOT / 'assets' / icon['output'], data)
    records.append({'id': icon['id'], 'source': icon['receipt']['path'],
                    'source_sha256': icon['receipt']['sha256'],
                    'output': 'assets/' + icon['output'], 'output_sha256': sha(data),
                    'source_kind': 'current_literal_svg'})
emit(ROOT / 'assets/synapse/audio-oled-artwork-assets.json', (json.dumps(records, indent=2) + '\n').encode())
entries = '\n'.join(f'    ("{r["output"].removeprefix("assets/")}", include_bytes!("{Path(r["output"]).name}")),' for r in records)
emit(ROOT / 'assets/synapse/audio-oled-artwork-embedded.rs', ('// Generated by tools/prepare-audio-oled-artwork-assets.py\n&[\n' + entries + '\n]\n').encode())
print(f'Prepared and validated {len(records)} current 1383 artwork assets; RGBA frames and animation timing preserved.')
