&[
    ("synapse/chroma-settings-back.svg", include_bytes!("chroma-settings-back.svg")),
    ("synapse/chroma-settings-forward.svg", include_bytes!("chroma-settings-forward.svg")),
    ("synapse/chroma-settings-refresh.svg", include_bytes!("chroma-settings-refresh.svg")),
    ("synapse/chroma-settings-help.svg", include_bytes!("chroma-settings-help.svg")),
    ("synapse/chroma-settings-check.svg", include_bytes!("chroma-settings-check.svg")),
    ("synapse/chroma-settings-logo.svg", include_bytes!("chroma-settings-logo.svg")),
    ("synapse/chroma-settings-logo-beta.svg", include_bytes!("chroma-settings-logo-beta.svg")),
    ("synapse/chroma-settings-warning.svg", include_bytes!("chroma-settings-warning.svg")),
    ("synapse/chroma-settings-wdl.svg", include_bytes!("chroma-settings-wdl.svg")),
    ("synapse/chroma-settings-facebook.svg", include_bytes!("chroma-settings-facebook.svg")),
    ("synapse/chroma-settings-facebook-hover.svg", include_bytes!("chroma-settings-facebook-hover.svg")),
    ("synapse/chroma-settings-ig.svg", include_bytes!("chroma-settings-ig.svg")),
    ("synapse/chroma-settings-ig-hover.svg", include_bytes!("chroma-settings-ig-hover.svg")),
    ("synapse/chroma-settings-twitter.svg", include_bytes!("chroma-settings-twitter.svg")),
    ("synapse/chroma-settings-twitter-hover.svg", include_bytes!("chroma-settings-twitter-hover.svg")),
    ("synapse/chroma-settings-youtube.svg", include_bytes!("chroma-settings-youtube.svg")),
    ("synapse/chroma-settings-youtube-hover.svg", include_bytes!("chroma-settings-youtube-hover.svg")),
    ("synapse/chroma-settings-tiktok.svg", include_bytes!("chroma-settings-tiktok.svg")),
    ("synapse/chroma-settings-tiktok-hover.svg", include_bytes!("chroma-settings-tiktok-hover.svg")),
    ("synapse/chroma-settings-twitch.svg", include_bytes!("chroma-settings-twitch.svg")),
    ("synapse/chroma-settings-twitch-hover.svg", include_bytes!("chroma-settings-twitch-hover.svg")),
    ("synapse/chroma-settings-discord.svg", include_bytes!("chroma-settings-discord.svg")),
    ("synapse/chroma-settings-discord-hover.svg", include_bytes!("chroma-settings-discord-hover.svg")),
    ("synapse/chroma-settings-insider.svg", include_bytes!("chroma-settings-insider.svg")),
    ("synapse/chroma-settings-insider-hover.svg", include_bytes!("chroma-settings-insider-hover.svg")),
]
