&[
    ("synapse/gamepad-2636-calibration-steps-1.svg", include_bytes!("gamepad-2636-calibration-steps-1.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-steps-2.svg", include_bytes!("gamepad-2636-calibration-steps-2.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-steps-3.svg", include_bytes!("gamepad-2636-calibration-steps-3.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-steps-4.svg", include_bytes!("gamepad-2636-calibration-steps-4.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-steps-5.svg", include_bytes!("gamepad-2636-calibration-steps-5.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-steps-6.svg", include_bytes!("gamepad-2636-calibration-steps-6.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-thumbstick.svg", include_bytes!("gamepad-2636-calibration-thumbstick.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-bumper.svg", include_bytes!("gamepad-2636-calibration-bumper.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-warning.svg", include_bytes!("gamepad-2636-calibration-warning.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-simulator.svg", include_bytes!("gamepad-2636-calibration-simulator.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-direction-1-rest.svg", include_bytes!("gamepad-2636-calibration-direction-1-rest.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-direction-1-edge.svg", include_bytes!("gamepad-2636-calibration-direction-1-edge.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-direction-2-rest.svg", include_bytes!("gamepad-2636-calibration-direction-2-rest.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-direction-2-edge.svg", include_bytes!("gamepad-2636-calibration-direction-2-edge.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-direction-3-rest.svg", include_bytes!("gamepad-2636-calibration-direction-3-rest.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-direction-3-edge.svg", include_bytes!("gamepad-2636-calibration-direction-3-edge.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-direction-4-rest.svg", include_bytes!("gamepad-2636-calibration-direction-4-rest.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-direction-4-edge.svg", include_bytes!("gamepad-2636-calibration-direction-4-edge.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-direction-5-rest.svg", include_bytes!("gamepad-2636-calibration-direction-5-rest.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-direction-5-edge.svg", include_bytes!("gamepad-2636-calibration-direction-5-edge.svg") as &[u8]),
    ("synapse/gamepad-2636-calibration-edition-0.png", include_bytes!("gamepad-2636-calibration-edition-0.png") as &[u8]),
    ("synapse/gamepad-2636-calibration-edition-128.png", include_bytes!("gamepad-2636-calibration-edition-128.png") as &[u8]),
    ("synapse/gamepad-2636-calibration-edition-129.png", include_bytes!("gamepad-2636-calibration-edition-129.png") as &[u8]),
]
