&[
    ("synapse/gamepad-2676-calibration-selection-edition-0.svg", include_bytes!("gamepad-2676-calibration-selection-edition-0.svg") as &[u8]),
    ("synapse/gamepad-2676-calibration-trigger-artwork-edition-0.svg", include_bytes!("gamepad-2676-calibration-trigger-artwork-edition-0.svg") as &[u8]),
    ("synapse/gamepad-2676-calibration-connectors-0.svg", include_bytes!("gamepad-2676-calibration-connectors-0.svg") as &[u8]),
    ("synapse/gamepad-2676-calibration-connectors-1.svg", include_bytes!("gamepad-2676-calibration-connectors-1.svg") as &[u8]),
    ("synapse/gamepad-2676-calibration-connectors-2.svg", include_bytes!("gamepad-2676-calibration-connectors-2.svg") as &[u8]),
    ("synapse/gamepad-2676-calibration-connectors-3.svg", include_bytes!("gamepad-2676-calibration-connectors-3.svg") as &[u8]),
    ("synapse/gamepad-2676-calibration-connectors-4.svg", include_bytes!("gamepad-2676-calibration-connectors-4.svg") as &[u8]),
    ("synapse/gamepad-2676-trigger-steps-1.svg", include_bytes!("gamepad-2676-trigger-steps-1.svg") as &[u8]),
    ("synapse/gamepad-2676-trigger-steps-2.svg", include_bytes!("gamepad-2676-trigger-steps-2.svg") as &[u8]),
    ("synapse/gamepad-2676-trigger-meter-template.svg", include_bytes!("gamepad-2676-trigger-meter-template.svg") as &[u8]),
    ("synapse/gamepad-2676-trigger-timer-template.svg", include_bytes!("gamepad-2676-trigger-timer-template.svg") as &[u8]),
    ("synapse/gamepad-2676-trigger-warning.svg", include_bytes!("gamepad-2676-trigger-warning.svg") as &[u8]),
    ("synapse/gamepad-2684-calibration-selection-edition-0.svg", include_bytes!("gamepad-2684-calibration-selection-edition-0.svg") as &[u8]),
    ("synapse/gamepad-2684-calibration-trigger-artwork-edition-0.svg", include_bytes!("gamepad-2684-calibration-trigger-artwork-edition-0.svg") as &[u8]),
    ("synapse/gamepad-2684-calibration-connectors-0.svg", include_bytes!("gamepad-2684-calibration-connectors-0.svg") as &[u8]),
    ("synapse/gamepad-2684-calibration-connectors-1.svg", include_bytes!("gamepad-2684-calibration-connectors-1.svg") as &[u8]),
    ("synapse/gamepad-2684-calibration-connectors-2.svg", include_bytes!("gamepad-2684-calibration-connectors-2.svg") as &[u8]),
    ("synapse/gamepad-2684-calibration-connectors-3.svg", include_bytes!("gamepad-2684-calibration-connectors-3.svg") as &[u8]),
    ("synapse/gamepad-2684-calibration-connectors-4.svg", include_bytes!("gamepad-2684-calibration-connectors-4.svg") as &[u8]),
    ("synapse/gamepad-2684-trigger-steps-1.svg", include_bytes!("gamepad-2684-trigger-steps-1.svg") as &[u8]),
    ("synapse/gamepad-2684-trigger-steps-2.svg", include_bytes!("gamepad-2684-trigger-steps-2.svg") as &[u8]),
    ("synapse/gamepad-2684-trigger-meter-template.svg", include_bytes!("gamepad-2684-trigger-meter-template.svg") as &[u8]),
    ("synapse/gamepad-2684-trigger-timer-template.svg", include_bytes!("gamepad-2684-trigger-timer-template.svg") as &[u8]),
    ("synapse/gamepad-2684-trigger-warning.svg", include_bytes!("gamepad-2684-trigger-warning.svg") as &[u8]),
]
