// Generated by tools/prepare-settings-window-assets.py
&[
    ("synapse/settings-window-logo.svg", include_bytes!("settings-window-logo.svg")),
    ("synapse/settings-window-back.svg", include_bytes!("settings-window-back.svg")),
    ("synapse/settings-window-forward.svg", include_bytes!("settings-window-forward.svg")),
    ("synapse/settings-window-refresh.svg", include_bytes!("settings-window-refresh.svg")),
]
