// Generated by tools/prepare-tray-account-assets.py
&[
    ("synapse/tray-guest-current.svg", include_bytes!("tray-guest-current.svg")),
    ("synapse/tray-user-current.svg", include_bytes!("tray-user-current.svg")),
    ("synapse/tray-settings-current.svg", include_bytes!("tray-settings-current.svg")),
]
